SELECT RA_FILIAL AS FILIAL, RA_MAT AS MAT, RA_NOME AS NOME, RA_CC AS CCUSTO, 
CTT_DESC01 AS DESC_CCUSTO,RA_CODFUNC AS COD_FUNC, RJ_DESC AS FUNCAO,
CONVERT(VARCHAR , CAST ( RA_ADMISSA AS DATETIME ), 103) AS ADMISSAO,
CONVERT(VARCHAR , CAST ( RA_DEMISSA AS DATETIME ), 103) AS DEMISSAO
FROM SRA010
INNER JOIN CTT010 ON CTT_CUSTO =RA_CC AND CTT010.D_E_L_E_T_= ''
INNER JOIN SRJ010 ON RJ_FUNCAO =RA_CODFUNC AND SRJ010.D_E_L_E_T_= ''
WHERE RA_SITFOLH ='D' AND SRA010.D_E_L_E_T_= '' AND RA_DEMISSA>='20141101'

SELECT RA_FILIAL AS FILIAL, RA_MAT AS MAT, RA_NOME AS NOME , RA_CIC AS CPF, RA_CC AS CCUSTO , CTT_DESC01 AS DESC_CCUSTO, RJ_DESC AS FUNCAO ,
CONVERT(VARCHAR , CAST ( RA_ADMISSA AS DATETIME ), 103 ) AS ADMISSAO,
(CASE RA_SITFOLH WHEN 'A' THEN 'AFASTADO' WHEN 'F' THEN 'FERIAS' WHEN 'T' THEN 'TRANSFERIDO' ELSE 'ATIVO' END) SITUACAO
FROM SRA010
INNER JOIN CTT010 ON CTT_CUSTO =RA_CC AND CTT010.D_E_L_E_T_= ''
INNER JOIN SRJ010 ON RJ_FUNCAO =RA_CODFUNC AND SRJ010.D_E_L_E_T_= ''
WHERE RA_SITFOLH <>'D' AND RA_ADMISSA >= '20141101' AND SRA010.D_E_L_E_T_ = ''
