--Relatório de DE PARA com a DIRF
SELECT R4_FILIAL, R4_MAT, R4_CPFCGC, RA_NOME, R4_MES, R4_TIPOREN, DIRF, ACUMULADO, DIRF - ACUMULADO AS DIF
FROM ( SELECT R4_FILIAL, R4_MAT, R4_CPFCGC, RA_NOME, R4_MES, R4_TIPOREN, DIRF,
(CASE WHEN ACUMULADO2 < 0 THEN ROUND(ACUMULADO2*-1,2) ELSE ROUND(ACUMULADO2,2) END)+
ISNULL((SELECT SUM(RD_VALOR) FROM SRD020 A, SRV020 B
WHERE RD_PD=RV_COD AND A.RD_FILIAL=R4_FILIAL AND A.RD_MAT=R4_MAT AND R4_MES=SUBSTRING(RD_DATPGT,5,2) AND R4_TIPOREN=RV_DIRF
AND A.D_E_L_E_T_='' AND B.D_E_L_E_T_='' AND RD_DATPGT BETWEEN '20140101' AND '20141231' AND RV_DIRF = 'R'
GROUP BY RD_FILIAL, RD_MAT, RV_DIRF, SUBSTRING(RD_DATPGT,5,2)),0) ACUMULADO FROM (
SELECT  R4_FILIAL, R4_MAT, R4_CPFCGC, RA_NOME, R4_MES, R4_TIPOREN, DIRF, ACUMULADO1  AS ACUMULADO2
FROM (SELECT R4_FILIAL, R4_MAT, R4_CPFCGC, RA_NOME, R4_MES, R4_TIPOREN, R4_VALOR DIRF,ISNULL((SELECT SUM(RD_VALOR) FROM SRD020 A, SRV020 B
WHERE RD_PD=RV_COD AND A.RD_FILIAL=R4_FILIAL AND A.RD_MAT=R4_MAT AND R4_MES=SUBSTRING(RD_DATPGT,5,2) AND R4_TIPOREN=RV_DIRF
AND A.D_E_L_E_T_='' AND B.D_E_L_E_T_='' AND RD_DATPGT BETWEEN '20140101' AND '20141231' AND RV_DIRF <> '' 
AND (RV_TIPOCOD='1'  OR RV_DIRF='R')
GROUP BY RD_FILIAL, RD_MAT, RV_DIRF, SUBSTRING(RD_DATPGT,5,2)),0) -
ISNULL((SELECT SUM(RD_VALOR) FROM SRD020 A, SRV020 B
WHERE RD_PD=RV_COD AND A.RD_FILIAL=R4_FILIAL AND A.RD_MAT=R4_MAT AND R4_MES=SUBSTRING(RD_DATPGT,5,2) AND R4_TIPOREN=RV_DIRF
AND A.D_E_L_E_T_='' AND B.D_E_L_E_T_='' AND RD_DATPGT BETWEEN '20140101' AND '20141231' AND RV_DIRF <> '' 
AND (RV_TIPOCOD IN ('2','3') OR RV_DIRF='R')
GROUP BY RD_FILIAL, RD_MAT, RV_DIRF, SUBSTRING(RD_DATPGT,5,2)),0)
ACUMULADO1
 FROM SR4020 R4, SRA020 RA
WHERE R4_FILIAL=RA_FILIAL AND R4_MAT=RA_MAT AND R4.D_E_L_E_T_='' AND R4_ANO='2014'
--AND R4_MAT='000488' 
)T)X)Y

--RELATÓRIO PARA CONFERENCIA DA DIRF, SOMENTE VALORES DO ACUMULADOS
SELECT RD_FILIAL FILIAL, RD_MAT MAT, RA_NOME NOME, RD_PD COD_VERBA, RV_DESC VERBA_DESC, 
CASE RV_TIPOCOD WHEN '1' THEN 'PROVENTO' WHEN '2' THEN 'DESCONTO' WHEN '3' THEN 'BASE' ELSE 'ERROR' END AS TIPO,
RV_DIRF DIRF, X5_DESCRI DIRF_DESC,RD_HORAS REF, RD_VALOR VALOR,
CONVERT(VARCHAR , CAST ( RD_DATPGT AS DATETIME ), 103 ) AS DT_PGMT,
SUBSTRING(RD_DATPGT,5,2) MES,
RA_CIC CPF,
CONVERT(VARCHAR , CAST ( RA_ADMISSA AS DATETIME ), 103 ) AS ADMISSAO,
CASE WHEN RA_DEMISSA <> '' THEN CONVERT(VARCHAR , CAST ( RA_DEMISSA AS DATETIME ), 103 )
ELSE '' END AS DEMISSAO
 FROM SRD020 A, SRA020 B, SRV020 C, SX5020 X
WHERE RA_FILIAL=RD_FILIAL AND RD_MAT=RA_MAT AND RV_COD=RD_PD AND
X5_TABELA='36' AND RV_DIRF=X5_CHAVE 
AND RD_DATPGT BETWEEN '20140101' AND '20141231'
AND A.D_E_L_E_T_='' AND B.D_E_L_E_T_='' AND C.D_E_L_E_T_='' AND X.D_E_L_E_T_='' 

--UPDATE PARA AJUSTAR O TIPO DE RETENÇÃO A 
/*
UPDATE SRD020
SET R_E_C_D_E_L_= R_E_C_N_O_,
D_E_L_E_T_='*'
WHERE --RD_MAT='000589' AND 
RD_PD='430' AND RD_DATPGT BETWEEN '20130101' AND '20141231' AND
R_E_C_D_E_L_='' AND D_E_L_E_T_=''
*/

--ROLLBACK PARA AJUSTE DO TIPO DE RETENÇÃO A
/*
UPDATE SRD020
SET R_E_C_D_E_L_= 0,
D_E_L_E_T_=''
WHERE --RD_MAT='000589' AND 
RD_PD='430' AND RD_DATPGT BETWEEN '20130101' AND '20141231' AND
R_E_C_D_E_L_<>'' AND D_E_L_E_T_<>''
*/