SELECT RD_FILIAL, RD_MAT, RD_PD, RV_DESC, 
CASE 
	WHEN RV_TIPOCOD ='1' THEN 'PROV'
	WHEN RV_TIPOCOD ='2' THEN 'DESC'
	ELSE 'BASE'
END TIPO, 
RD_HORAS, 
CASE 
	WHEN RV_TIPOCOD ='1' THEN RD_VALOR
	WHEN RV_TIPOCOD ='2' THEN RD_VALOR*-1
	ELSE RD_VALOR
END VALOR, 
RD_DATARQ, RD_DATPGT, RV_RAIS FROM SRD020 A, SRV020 B, SRA020 C
WHERE A.D_E_L_E_T_='' AND B.D_E_L_E_T_='' AND C5
AND A.RD_PD=B.RV_COD AND RD_DATARQ BETWEEN '201401' AND '201499'
 --AND RD_FILIAL='02' AND RD_MAT='010071'
 ORDER BY 1,2,8,3

 SELECT * FROM RCU020
 WHERE RCU_ANO='2014' AND D_E_L_E_T_=''

 SELECT RD_FILIAL, RD_MAT, RD_DATARQ, TOTAL, PROVENTO, DESCONTO, PROVENTO-DESCONTO AS LIQ
 FROM (SELECT RD_FILIAL, RD_MAT, RD_DATARQ, SUM(RD_VALOR)TOTAL,
isnull((SELECT SUM(RD_VALOR) FROM SRD020 D, SRV020 V
WHERE D.D_E_L_E_T_='' AND V.D_E_L_E_T_='' AND RD_PD=RV_COD AND
RD_FILIAL=A.RD_FILIAL AND RD_MAT=A.RD_MAT AND RV_TIPOCOD='1'
AND LEFT(RV_RAIS,1)='A' AND RD_DATARQ = A.RD_DATARQ
GROUP BY RD_FILIAL, RD_MAT, RD_DATARQ),0) PROVENTO,
isnull((SELECT SUM(RD_VALOR) FROM SRD020 D, SRV020 V
WHERE D.D_E_L_E_T_='' AND V.D_E_L_E_T_='' AND RD_PD=RV_COD AND
RD_FILIAL=A.RD_FILIAL AND RD_MAT=A.RD_MAT AND RV_TIPOCOD='2'
AND LEFT(RV_RAIS,1)='A' AND RD_DATARQ = A.RD_DATARQ
GROUP BY RD_FILIAL, RD_MAT, RD_DATARQ),0) DESCONTO
FROM SRD020 A, SRV020 B
WHERE RD_PD=RV_COD AND RD_FILIAL='02' AND RD_MAT='010071'
AND RD_DATARQ BETWEEN '201401' AND '201499' AND LEFT(RV_RAIS,1)='A' AND A.D_E_L_E_T_='' AND B.D_E_L_E_T_=''
GROUP BY RD_FILIAL, RD_MAT, RD_DATARQ, LEFT(RV_RAIS,1)
)T
ORDER BY RD_DATARQ