--RELATÓRIO PARA CONFERENCIA DA DIRF, SOMENTE VALORES DO ACUMULADOS
SELECT RD_FILIAL FILIAL, RD_MAT MAT, RA_NOME NOME, RD_PD COD_VERBA, RV_DESC VERBA_DESC, 
CASE RV_TIPOCOD WHEN '1' THEN 'PROVENTO' WHEN '2' THEN 'DESCONTO' WHEN '3' THEN 'BASE' ELSE 'ERROR' END AS TIPO,
RV_DIRF DIRF, X5_DESCRI DIRF_DESC,RD_HORAS REF, RD_VALOR VALOR,
CONVERT(VARCHAR , CAST ( RD_DATPGT AS DATETIME ), 103 ) AS DT_PGMT,
SUBSTRING(RD_DATPGT,5,2) MES,
RA_CIC CPF,
CONVERT(VARCHAR , CAST ( RA_ADMISSA AS DATETIME ), 103 ) AS ADMISSAO,
CASE WHEN RA_DEMISSA <> '' THEN CONVERT(VARCHAR , CAST ( RA_DEMISSA AS DATETIME ), 103 )
ELSE '' END AS DEMISSAO
 FROM SRD020 A, SRA020 B, SRV020 C, SX5020 X
WHERE RA_FILIAL=RD_FILIAL AND RD_MAT=RA_MAT AND RV_COD=RD_PD AND
X5_TABELA='36' AND RV_DIRF=X5_CHAVE 
AND RD_DATPGT BETWEEN '20140101' AND '20141231'
AND A.D_E_L_E_T_='' AND B.D_E_L_E_T_='' AND C.D_E_L_E_T_='' AND X.D_E_L_E_T_='' 

-- 1º --CONFERENCIA ACUMULADO VS GERA ARQUIVO (DIRF)
SELECT RD_FILIAL, RD_MAT, TIPORET='C1', VERBA='470', ANO='2014',
(SELECT SUM(X.RCS_VALOR) FROM RCS020 X
WHERE X.RCS_FILIAL=RD_FILIAL AND X.RCS_MAT=RD_MAT AND X.RCS_TIPORE='C1' AND X.RCS_VERBA='470' AND X.RCS_ANO='2014' AND X.D_E_L_E_T_=''
GROUP BY RCS_FILIAL,RCS_MAT, RCS_TIPORE) VALOR_DEFAULT, SUM(RD_VALOR) VALOR_OK FROM SRD020
WHERE  RD_PD IN ('473','474')
AND RD_DATPGT BETWEEN '20140101' AND '20141231'  
AND RD_FILIAL+RD_MAT IN (SELECT RD_FILIAL+RD_MAT FROM SRD020
WHERE  RD_PD = '473' AND RD_DATPGT BETWEEN '20140101' AND '20141231')
GROUP BY RD_FILIAL, RD_MAT

-- 2º --CRIAÇÃO DA TAB TEMPORARIA PARA UPDATE
SELECT * INTO SRD_C1 FROM(
SELECT RD_FILIAL, RD_MAT, TIPORET='C1', VERBA='470', ANO='2014', SUM(RD_VALOR) VALOR_OK FROM SRD020
WHERE  RD_PD IN ('473')
AND RD_DATPGT BETWEEN '20140101' AND '20141231'  
AND RD_FILIAL+RD_MAT IN (SELECT RD_FILIAL+RD_MAT FROM SRD020
WHERE  RD_PD = '473' AND RD_DATPGT BETWEEN '20140101' AND '20141231')
GROUP BY RD_FILIAL, RD_MAT
)SRD_C1

-- 3º --UPDATE PARA ATUALIZAÇÃO DA RCS (ITENS DIRF) CONFORME ACUMULADOS DA VERBA 473+474 PARA FUNCIONARIOS COM PENSÃO
UPDATE RCS020
SET RCS_VALOR = VALOR_OK
FROM RCS020 A, SRD_C1 B
WHERE A.RCS_FILIAL=B.RD_FILIAL AND A.RCS_MAT=B.RD_MAT 
AND RCS_TIPORE=B.TIPORET AND A.RCS_ANO=B.ANO AND A.RCS_VERBA=B.VERBA
AND A.D_E_L_E_T_='' AND A.RCS_VALOR < B.VALOR_OK


