FILIAL + VALOR

select RA_FILIAL,RA_MAT,RA_NOME,RA_CIC,RA_CC,RC_PD,RV_DESC,RC_HORAS,RC_VALOR
from SRA010 A,SRC010 B, SRV010 C
where RA_FILIAL = RC_FILIAL 
and RA_MAT = RC_MAT 
and RC_PD = RV_COD 
and RA_FILIAL = '014NE004'
and RC_VALOR = '72.60'
and A.D_E_L_E_T_ = ' '
and B.D_E_L_E_T_ = ' '
and C.D_E_L_E_T_ = ' '
ORDER BY RC_PD,RA_MAT

VALOR NO CT2

SELECT * FROM CT2010 WHERE CT2_DATA = '20121231' 
AND CT2_LOTE = '008890' 
and D_E_L_E_T_ = ' ' 
AND CT2_FILIAL = '001NE003'
AND CT2_VALOR = '550.55'

VALOR DA VERBA

select RA_FILIAL,RA_MAT,RTRIM(RA_NOME),RA_SITFOLH,RA_DEMISSA,RA_CIC,RA_CC,RC_PD,RV_DESC,RC_HORAS,RC_VALOR
from SRA010 A,SRC010 B, SRV010 C
where RA_FILIAL = RC_FILIAL 
and RA_MAT = RC_MAT 
and RC_PD = RV_COD 
and RC_PD = '993'
and RC_FILIAL = '013NE005'
and A.D_E_L_E_T_ = ' '
and B.D_E_L_E_T_ = ' '
and C.D_E_L_E_T_ = ' '
ORDER BY RA_FILIAL,RA_MAT


VALOR DE VARIAS VERBAS

select RA_FILIAL,RA_MAT,RTRIM(RA_NOME),RA_SITFOLH,RA_DEMISSA,RA_CIC,RA_CC,RC_PD,RV_DESC,RC_HORAS,RC_VALOR
from SRA010 A,SRC010 B, SRV010 C
where RA_FILIAL = RC_FILIAL 
and RA_MAT = RC_MAT 
and RC_PD = RV_COD 
and RC_FILIAL = '001NE001'
and RC_PD in ('765','767','768','769','772','780','993')
and A.D_E_L_E_T_ = ' '
and B.D_E_L_E_T_ = ' '
and C.D_E_L_E_T_ = ' '
ORDER BY RC_VALOR

MATRICULA

select RA_FILIAL,RA_MAT,RTRIM(RA_NOME),RA_SITFOLH,RA_DEMISSA,RA_CIC,RA_CC,RC_PD,RV_DESC,RC_HORAS,RC_VALOR
from SRA010 A,SRC010 B, SRV010 C
where RA_FILIAL = RC_FILIAL 
and RA_MAT = RC_MAT 
and RC_PD = RV_COD 
and RC_FILIAL = '001NE001'
and RC_MAT = '000866'
and A.D_E_L_E_T_ = ' '
and B.D_E_L_E_T_ = ' '
and C.D_E_L_E_T_ = ' '
ORDER BY RC_PD

