SELECT * FROM ConSituacoes

SELECT * FROM MotivosSituacoes

SELECT CST_CdiContratado,
CST_DtdSituacaoInicio R8_DATA,
CASE WHEN CST_CdiSituacao IN ('1','3','6','7','8','12') THEN 'O'
	WHEN CST_CdiSituacao IN ('2','4','5','9','10','11') THEN 'P'
	WHEN CST_CdiSituacao IN ('14','15','16') THEN 'Q'
	WHEN CST_CdiSituacao IN ('13','17') THEN 'X'
	ELSE 'L'
END AS R8_TIPO,
CST_DtdSituacaoInicio R8_DATAINI, 
CST_DtdSituacaoFim R8_DATAFIM, 
CST_QtiDiasNaSituacao R8_DURACAO FROM ConSituacoes

SELECT DISTINCT CST_CdiSituacao, COUNT(CST_CdiSituacao) FROM ConSituacoes
GROUP BY CST_CdiSituacao

SELECT RA_FILIAL, RA_MAT, CST_CdiContratado,
CONVERT(VARCHAR , CST_DtdSituacaoInicio , 103 ) R8_DATA,CST_CdiSituacao,
CASE WHEN CST_CdiSituacao IN ('1','3','6','7','8','12') THEN 'O'
	WHEN CST_CdiSituacao IN ('2','4','5','9','10','11') THEN 'P'
	WHEN CST_CdiSituacao IN ('14','15','16') THEN 'Q'
	WHEN CST_CdiSituacao IN ('13','17') THEN 'X'
	ELSE 'L'
END AS R8_TIPO,
CONVERT(VARCHAR , CST_DtdSituacaoInicio, 103 ) R8_DATAINI, 
CASE WHEN CST_DtdSituacaoFim IS NULL THEN '' ELSE CONVERT(VARCHAR , CST_DtdSituacaoFim , 103 ) END R8_DATAFIM, 
CST_QtiDiasNaSituacao R8_DURACAO FROM [apcmp].[dbo].[ConSituacoes], [TOTVS_CMP].[dbo].[SRA990] B
WHERE RA_CRACHA=CST_CdiContratado AND RA_CRACHA='100000591'
ORDER BY CST_CdiContratado,CST_DtdSituacaoInicio


SELECT * INTO SR8BASE1 FROM (SELECT RH_FILIAL R8_FILIAL, RH_MAT R8_MAT, RH_DATAINI R8_DATA, 'F' R8_TIPO, RH_DATAINI R8_DATAINI,
RH_DATAFIM R8_DATAFIM, RH_DFERIAS R8_DURACAO FROM [TOTVS_CMP].[dbo].[SRH_TOSR8]
UNION ALL
SELECT RA_FILIAL, RA_MAT,
CONVERT(VARCHAR , CST_DtdSituacaoInicio , 112 ) R8_DATA,
CASE WHEN CST_CdiSituacao IN ('1','3','6','7','8','12') THEN 'O'
	WHEN CST_CdiSituacao IN ('2','4','5','9','10','11') THEN 'P'
	WHEN CST_CdiSituacao IN ('14','15','16') THEN 'Q'
	WHEN CST_CdiSituacao IN ('13','17') THEN 'X'
	ELSE 'L'
END AS R8_TIPO,
CONVERT(VARCHAR , CST_DtdSituacaoInicio, 112 ) R8_DATAINI, 
CASE WHEN CST_DtdSituacaoFim IS NULL THEN '' ELSE CONVERT(VARCHAR , CST_DtdSituacaoFim , 112 ) END R8_DATAFIM, 
CST_QtiDiasNaSituacao R8_DURACAO FROM ConSituacoes, [TOTVS_CMP].[dbo].[SRA990] B
WHERE RA_CRACHA=CST_CdiContratado)T

SELECT RA_CRACHA,* FROM [TOTVS_CMP].[dbo].[SRA990] B
WHERE RA_MAT='000326' AND RA_FILIAL='02'

SELECT R8_FILIAL, R8_MAT, ROW_NUMBER() OVER(PARTITION BY R8_FILIAL+R8_MAT ORDER BY R8_FILIAL+R8_MAT+R8_DATA) R8_SEQ,
R8_DATA, R8_TIPO, R8_DATAINI, R8_DATAFIM, R8_DURACAO
FROM SR8BASE1
ORDER BY 1,2,4,3

SELECT R8_FILIAL, R8_MAT,
CONVERT(VARCHAR , EOMONTH(CAST ( R8_DATA AS DATETIME )), 103 )R8_DATA, R8_TIPO, 
CONVERT(VARCHAR , EOMONTH(CAST ( R8_DATAINI AS DATETIME )), 103 )R8_DATAINI, 
CASE WHEN R8_DATAFIM = '' THEN ''
ELSE CONVERT(VARCHAR , EOMONTH(CAST ( R8_DATAFIM AS DATETIME )), 103 ) END R8_DATAFIM, R8_DURACAO
 FROM [TOTVS_CMP].[dbo].[SR8990]
 UNION ALL
SELECT R8_FILIAL, R8_MAT,
CONVERT(VARCHAR , EOMONTH(CAST ( R8_DATA AS DATETIME )), 103 )R8_DATA, R8_TIPO, 
CONVERT(VARCHAR , EOMONTH(CAST ( R8_DATAINI AS DATETIME )), 103 )R8_DATAINI, 
CONVERT(VARCHAR , EOMONTH(CAST ( R8_DATAFIM AS DATETIME )), 103 )R8_DATAFIM, R8_DURACAO
 FROM SR8BASE2 --ORDER BY 2,3

 SELECT * FROM SR81
 SELECT * FROM SR82

 UPDATE SR81
 SET R8_SEQ = CONCAT(REPLICATE('0',3-LEN(B.R8_SEQ1)),B.R8_SEQ1)
 FROM SR81 A, SR82 B
 WHERE A.R8_FILIAL+A.R8_MAT+A.R8_DATA+A.R8_TIPO+A.R8_DATAINI+A.R8_DATAFIM=B.R8_FILIAL+B.R8_MAT+B.R8_DATA+B.R8_TIPO+B.R8_DATAINI+B.R8_DATAFIM

 SELECT CONCAT(REPLICATE('0',3-LEN(B.R8_SEQ1)),B.R8_SEQ1),
 CONCAT(B.R8_SEQ1,B.R8_SEQ1),* FROM SR81 A, SR82 B
 WHERE A.R8_FILIAL+A.R8_MAT+A.R8_DATA+A.R8_TIPO+A.R8_DATAINI+A.R8_DATAFIM=B.R8_FILIAL+B.R8_MAT+B.R8_DATA+B.R8_TIPO+B.R8_DATAINI+B.R8_DATAFIM

 SELECT A.R8_FILIAL,A.R8_MAT,A.R8_DATA,A.R8_DATAINI,A.R8_DATAFIM FROM SR81 A
 --WHERE R8_MAT='014076'
 GROUP BY A.R8_FILIAL,A.R8_MAT,A.R8_DATA,A.R8_DATAINI,A.R8_DATAFIM
HAVING COUNT (*) > 1

SELECT R8_FILIAL, R8_MAT,
CONVERT(VARCHAR , EOMONTH(CAST ( R8_DATA AS DATETIME )), 103 )R8_DATA, R8_TIPO, 
CONVERT(VARCHAR , EOMONTH(CAST ( R8_DATAINI AS DATETIME )), 103 )R8_DATAINI, 
CASE WHEN R8_DATAFIM = '' THEN ''
ELSE CONVERT(VARCHAR , EOMONTH(CAST ( R8_DATAFIM AS DATETIME )), 103 ) END R8_DATAFIM, R8_DURACAO
 FROM [TOTVS_CMP].[dbo].[SR8990]
 UNION ALL
 SELECT RH_FILIAL AS R8_FILIAL, RH_MAT R8_MAT,
 CONVERT(VARCHAR , EOMONTH(CAST ( RH_DATAINI  AS DATETIME )), 103 )R8_DATA,'F' AS R8_TIPO, 
 CONVERT(VARCHAR , EOMONTH(CAST ( RH_DATAINI   AS DATETIME )), 103 )R8_DATAINI,
 CONVERT(VARCHAR , EOMONTH(CAST ( RH_DATAFIM  AS DATETIME )), 103 )R8_DATAFIM,
 RH_DFERIAS R8_DURACAO
  FROM SRH990
 WHERE RH_FILIAL+RH_MAT+RH_DATAINI+RH_DATAFIM NOT IN 
 (SELECT R8_FILIAL+R8_MAT+R8_DATAINI+R8_DATAFIM FROM SR8990)

 SELECT * INTO SR8992 FROM (
 SELECT R8_FILIAL, R8_MAT, R8_DATA, R8_TIPO, R8_DATAINI, R8_DATAFIM, R8_DURACAO
 FROM SR89911
 UNION ALL
 SELECT RA_FILIAL, RA_MAT, R8_DATA, R8_TIPO, R8_DATAINI, R8_DATAFIM, R8_DURACAO
 FROM SR8AFAST
 WHERE RA_FILIAL+RA_MAT+R8_DATAINI+R8_DATAFIM NOT IN (
 SELECT R8_FILIAL+R8_MAT+R8_DATAINI+R8_DATAFIM FROM SR89911)
 )T

 SELECT
 R8_FILIAL, R8_MAT,  --ROW_NUMBER () OVER(PARTITION BY R8_FILIAL, R8_MAT ORDER BY R8_FILIAL, R8_MAT, R8_DATA, R8_DATAINI) R8_SEQ ,
CONVERT(VARCHAR , CAST ( R8_DATA AS DATETIME ), 103 )R8_DATA, R8_TIPO, 
CONVERT(VARCHAR , CAST ( R8_DATAINI AS DATETIME ), 103 )R8_DATAINI, 
CASE WHEN R8_DATAFIM = '' THEN ''
ELSE CONVERT(VARCHAR , CAST ( R8_DATAFIM AS DATETIME ), 103 ) END R8_DATAFIM, R8_DURACAO
FROM SR8992
  WHERE R8_FILIAL+R8_MAT+R8_DATAINI+R8_DATAFIM NOT IN (
 SELECT R8_FILIAL+R8_MAT+R8_DATAINI+R8_DATAFIM FROM SR8990) AND R8_MAT='000005' AND R8_FILIAL='06'
 ORDER BY 1,2,3

 SELECT R8_FILIAL+R8_MAT+R8_DATAINI+R8_DATAFIM,* FROM SR8992
 WHERE R8_MAT='000005' AND R8_FILIAL='06' ORDER BY 4
SELECT R8_FILIAL+R8_MAT+R8_DATAINI+R8_DATAFIM,* FROM SR8990
WHERE R8_MAT='000005' AND R8_FILIAL='06' ORDER BY 4

DELETE SR8990
WHERE R8_DATA  < '20131201'

SELECT RA_CRACHA,* FROM SRA990
WHERE RA_MAT='000591' AND RA_FILIAL='01'

SELECT R8_FILIAL,R8_MAT,R8_DATAINI,R8_DATAFIM,R8_TIPO, COUNT(*) FROM SR8992
 --WHERE R8_MAT='008991' AND R8_FILIAL='01' 
GROUP BY R8_FILIAL,R8_MAT,R8_DATAINI,R8_DATAFIM,R8_TIPO
HAVING COUNT(*) > 1
ORDER BY 1,2

SELECT * INTO SR8990_SEQ FROM (SELECT REPLICATE('0',3-LEN(ROW_NUMBER () OVER(PARTITION BY R8_FILIAL, R8_MAT ORDER BY R8_FILIAL, R8_MAT, R8_DATA, R8_DATAINI)))+CONVERT(VARCHAR,  ROW_NUMBER () OVER(PARTITION BY R8_FILIAL, R8_MAT ORDER BY R8_FILIAL, R8_MAT, R8_DATA, R8_DATAINI))
 R8_SEQ1,* FROM SR8990)T

 UPDATE SR8990
 SET R8_SEQ = REPLICATE('0',3-LEN(ROW_NUMBER () OVER(PARTITION BY R8_FILIAL, R8_MAT ORDER BY R8_FILIAL, R8_MAT, R8_DATA, R8_DATAINI)))+CONVERT(VARCHAR,  ROW_NUMBER () OVER(PARTITION BY R8_FILIAL, R8_MAT ORDER BY R8_FILIAL, R8_MAT, R8_DATA, R8_DATAINI))
 FROM SR8990


 SELECT * FROM SR8_APPEND9901
 WHERE 
 R8_FILIAL+R8_MAT+R8_DATAINI+R8_DURACAO IN 
 (SELECT R8_FILIAL+R8_MAT+R8_DATAINI+R8_DURACAO FROM SR8990) AND
 R8_MAT='000005' AND R8_FILIAL='06'

SELECT  CASE WHEN R8_SEQ1 > 9 THEN '000'+CONVERT(VARCHAR,R8_SEQ1) ELSE '00'+CONVERT(VARCHAR,R8_SEQ1) END,* FROM SR990_SEQ

UPDATE SR990_SEQ
SET R8_SEQ1 = R8_SEQ1-100

SELECT * INTO SR990_SEQ1 FROM (SELECT 
CASE WHEN R8_SEQ1 < 10 THEN '00'+CONVERT(VARCHAR,R8_SEQ1) ELSE '0'+CONVERT(VARCHAR,R8_SEQ1) end R8_SEQ2
,* FROM SR990_SEQ)T

SELECT * FROM SR990_SEQ1

UPDATE SR8990
SET R8_SEQ=B.R8_SEQ
FROM SR8990 A, SR990_SEQ1 B
WHERE A.R_E_C_N_O_ = B.R_E_C_N_O_

SELECT SIT_D1sSituacao,* FROM ConSituacoes,  Situacoes
where --CST_CdiMotivoSituacao = MTS_CdiMotivoSituacao
 CST_CdiConSituacao = SIT_CdiSituacao

 SELECT MTS_D1sMotivoSituacao,* FROM ConSituacoes,  MotivosSituacoes
where CST_CdiMotivoSituacao = MTS_CdiMotivoSituacao 
AND CST_CdiMotivoSituacao <> '0'


SELECT * FROM ConSituacoes
SELECT * FROM MotivosSituacoes
SELECT * FROM Situacoes

SELECT * FROM [TOTVS_CMP].[dbo].[SRA990]
WHERE RA_CRACHA = '140000299'

SELECT * FROM ConFichaFinanceira
WHERE CFF_CdiContratado='150000346'

 SELECT CST_CdiContratado, CST_DtdSituacaoInicio, CST_DtdSituacaoFim, CST_QtiDiasNaSituacao, 
 CASE WHEN CST_CdiSituacao IN ('6','16','26') THEN 'O' 
	WHEN CST_CdiSituacao IN ('7','17','27') THEN 'P' 
	WHEN CST_CdiSituacao IN ('5','25') THEN 'Q' 
	WHEN CST_CdiSituacao IN ('51') THEN 'X' 
	ELSE 'XXX'
END TIPO,
CASE WHEN CST_QtiDiasNaSituacao <= 15 THEN CST_QtiDiasNaSituacao ELSE 15 END R8_DIAS FROM ConSituacoes
WHERE CST_CdiMotivoSituacao <> '0'


 SELECT RA_FILIAL, RA_MAT, RA_NOME,CST_CdiContratado, CST_DtdSituacaoInicio, CST_DtdSituacaoFim, CST_QtiDiasNaSituacao, 
 CASE WHEN CST_CdiSituacao IN ('6','16','26') THEN 'O' 
	WHEN CST_CdiSituacao IN ('7','17','27') THEN 'P' 
	WHEN CST_CdiSituacao IN ('5','25') THEN 'Q' 
	WHEN CST_CdiSituacao IN ('51') THEN 'X' 
	ELSE 'XXX'
END TIPO,
CASE WHEN CST_QtiDiasNaSituacao <= 15 THEN CST_QtiDiasNaSituacao ELSE 15 END R8_DIAS FROM ConSituacoes,[TOTVS_CMP].[dbo].[SRA990]
WHERE CST_CdiMotivoSituacao <> '0' AND RA_CRACHA=CST_CdiContratado
AND CST_CdiContratado = '100011652'
ORDER BY 1,2,5


 SELECT RA_FILIAL, RA_MAT, RA_NOME,CST_CdiContratado, 
 CONVERT(VARCHAR , (CAST ( CST_DtdSituacaoInicio AS DATETIME )), 103 )CST_DtdSituacaoInicio, 
 CONVERT(VARCHAR , (CAST ( CST_DtdSituacaoFim AS DATETIME )), 103 )CST_DtdSituacaoFim, 
 CST_QtiDiasNaSituacao, 
 CASE WHEN CST_CdiSituacao IN ('6','16','26') THEN 'O' 
	WHEN CST_CdiSituacao IN ('7','17','27') THEN 'P' 
	WHEN CST_CdiSituacao IN ('5','25') THEN 'Q' 
	WHEN CST_CdiSituacao IN ('51') THEN 'X' 
	ELSE 'Y'
END TIPO,
CASE WHEN CST_CdiSituacao IN ('16','17') THEN CST_QtiDiasNaSituacao ELSE 0 END R8_DIAS
,CST_CdiSituacao
 FROM ConSituacoes,[TOTVS_CMP].[dbo].[SRA990]
WHERE  RA_CRACHA=CST_CdiContratado AND CST_CdiSituacao NOT IN ('1','9','0','19')
AND CST_DtdSituacaoFim IS NOT NULL
ORDER BY 1,2,5

