SELECT C5_NUM FROM dbo.SC5010
WHERE C5_NUM like '%*%' 
AND D_E_L_E_T_ <> '*'

SELECT C6_NUM FROM SC6010
WHERE C6_NUM like '%*%'
AND D_E_L_E_T_ <> '*'

SELECT C9_PEDIDO FROM SC9010
WHERE C9_PEDIDO like '%*%'
AND D_E_L_E_T_ <> '*'

SELECT D2_PEDIDO,D2_DOC FROM SD2010
WHERE D2_PEDIDO like '%*%'
AND D_E_L_E_T_ <> '*'

SELECT DAI_PEDIDO FROM DAI010
WHERE DAI_PEDIDO like '%*%'
AND D_E_L_E_T_ <> '*'

SELECT E1_PEDIDO FROM SE1010
WHERE E1_PEDIDO like '%01%'
AND D_E_L_E_T_ <> '*'


