BEGIN TRANSACTION 

UPDATE SC5010 
SET D_E_L_E_T_ = '*' 
FROM  SC5010 SC5 
WHERE  SC5.D_E_L_E_T_<>'*' AND 
 0 = (SELECT COUNT(*) FROM SC6010 SC6 WHERE SC6.D_E_L_E_T_<>'*' AND C6_NUM = C5_NUM ) 
 
UPDATE SC6010 
SET D_E_L_E_T_ = '*' 
FROM  SC6010 SC6 
WHERE  SC6.D_E_L_E_T_<>'*' AND 
 0 = (SELECT COUNT(*) FROM SC5010 SC5 WHERE SC5.D_E_L_E_T_<>'*' AND C5_NUM = C6_NUM ) 
 
UPDATE SC9010 
SET D_E_L_E_T_ = '*' 
FROM  SC9010 SC9 
WHERE  SC9.D_E_L_E_T_<>'*' AND 
 0 = (SELECT COUNT(*) FROM SC5010 SC5 WHERE SC5.D_E_L_E_T_<>'*' AND C5_NUM = C9_PEDIDO ) 

--COMMIT
