SELECT  * 
FROM  SC5010 SC5 
WHERE  SC5.D_E_L_E_T_<>'*' AND 
 0 = (SELECT COUNT(*) FROM SA1010 SA1 WHERE SA1.D_E_L_E_T_<>'*' AND A1_COD = C5_CLIENTE AND A1_LOJA = C5_LOJAENT AND C5_TIPO IN ('N','P','I','C')) 
 
SELECT  * 
FROM  SC5010 SC5 
WHERE  SC5.D_E_L_E_T_<>'*' AND 
 0 = (SELECT COUNT(*) FROM SA2010 SA2 WHERE SA2.D_E_L_E_T_<>'*' AND A2_COD = C5_CLIENTE AND A2_LOJA = C5_LOJAENT AND C5_TIPO IN ('B','D')) 
