SELECT RD_FILIAL, RD_MAT, RA_NOME, RD_PD, RV.RV_DESC, RD_TIPO1, SUBSTRING(RD_DATARQ,5,2)+'/'+SUBSTRING(RD_DATARQ,1,4) AS REF,
SUM(RD_HORAS) RD_HORAS, 
CASE 
	WHEN RV.RV_TIPO <> 'H' 
		THEN SUM(RD.RD_VALOR)
	ELSE
	SUM(RD_HORAS) * (((SELECT MAX(RD_VALOR) FROM SRD010 RDX WHERE RDX.D_E_L_E_T_='' AND RDX.RD_DATARQ BETWEEN '201401' AND '201411'
					AND RDX.RD_PD ='851' AND RD.RD_FILIAL=RDX.RD_FILIAL AND RD.RD_MAT=RDX.RD_MAT)
					+(SELECT MAX(RD_VALOR) FROM SRD010 RDX WHERE RDX.D_E_L_E_T_='' AND RDX.RD_DATARQ BETWEEN '201401' AND '201411'
					   AND RDX.RD_PD ='851' AND RD.RD_FILIAL=RDX.RD_FILIAL AND RD.RD_MAT=RDX.RD_MAT)*((RV.RV_PERC-100)/100))/RA_HRSMES) 
END VLR_ATUAL
FROM SRD010 RD, SRA010 RA, SRV010 RV
WHERE RD.RD_FILIAL=RA.RA_FILIAL AND RD.RD_MAT=RA.RA_MAT AND RD.RD_PD=RV.RV_COD 
AND RD.D_E_L_E_T_='' AND RA.D_E_L_E_T_='' AND RV.D_E_L_E_T_='' AND RA.RA_SITFOLH <> 'D'
AND RV.RV_MED13 = 'S' AND RD_DATARQ BETWEEN '201401' AND '201411'
--AND RD_FILIAL='014NE004' AND RD_MAT='037716' --and RD_PD='130'
GROUP BY RD_FILIAL, RD_MAT, RA_NOME, RD_PD, RV.RV_DESC, RD_TIPO1,RD_DATARQ, RV.RV_PERC,RA_HRSMES, RV.RV_TIPO
ORDER BY 1,2,4,7