SELECT RD_FILIAL FILIAL, COUNT(DISTINCT(RD_MAT)) QNT_FUNC, SUBSTRING(RD_DATARQ,5,2)+'/'+SUBSTRING(RD_DATARQ,1,4) AS REF,
ISNULL((SELECT SUM(RD_VALOR) FROM SRD010 RD1 WHERE RD.RD_FILIAL=RD1.RD_FILIAL 
	AND RD1.D_E_L_E_T_='' AND RD1.RD_DATARQ=RD.RD_DATARQ AND RD1.RD_PD='701'
	GROUP BY RD1.RD_FILIAL, RD1.RD_DATARQ),'')'701',
ISNULL((SELECT SUM(RD_VALOR) FROM SRD010 RD2 WHERE RD.RD_FILIAL=RD2.RD_FILIAL 
	AND RD2.D_E_L_E_T_='' AND RD2.RD_DATARQ=RD.RD_DATARQ AND RD2.RD_PD='702'
	GROUP BY RD2.RD_FILIAL, RD2.RD_DATARQ),'')'702',
ISNULL((SELECT SUM(RD_VALOR) FROM SRD010 RD3 WHERE RD.RD_FILIAL=RD3.RD_FILIAL 
	AND RD3.D_E_L_E_T_='' AND RD3.RD_DATARQ=RD.RD_DATARQ AND RD3.RD_PD='703'
	GROUP BY RD3.RD_FILIAL, RD3.RD_DATARQ),'')'703',
ISNULL((SELECT SUM(RD_VALOR) FROM SRD010 RD4 WHERE RD.RD_FILIAL=RD4.RD_FILIAL 
	AND RD4.D_E_L_E_T_='' AND RD4.RD_DATARQ=RD.RD_DATARQ AND RD4.RD_PD='704'
	GROUP BY RD4.RD_FILIAL, RD4.RD_DATARQ),'')'704',
ISNULL((SELECT SUM(RD_VALOR) FROM SRD010 RD8 WHERE RD.RD_FILIAL=RD8.RD_FILIAL 
	AND RD8.D_E_L_E_T_='' AND RD8.RD_DATARQ=RD.RD_DATARQ AND RD8.RD_PD='708'
	GROUP BY RD8.RD_FILIAL, RD8.RD_DATARQ),'')'708'
 FROM SRD010 RD, SRA010 RA
WHERE RD.D_E_L_E_T_='' AND RA.D_E_L_E_T_=''
AND RD_DATARQ BETWEEN '201205' AND '201410' AND RD_PD IN ('701', '702', '703', '704', '708')
AND RD_FILIAL BETWEEN '001NE001' AND '001NE999'
AND RA.RA_FILIAL=RD.RD_FILIAL AND RA.RA_MAT= RD.RD_MAT AND RA.RA_CATFUNC NOT IN ('E','G','P','A')
GROUP BY RD_FILIAL, RD_DATARQ
ORDER BY 3,1

--SELECT DISTINCT(RD_MAT),SUM(RD_VALOR) FROM SRD010
--WHERE RD_DATARQ = '201205' AND RD_PD IN ('702')--, '702', '703', '704', '708')
--AND D_E_L_E_T_='' AND RD_FILIAL='001NE001'
--GROUP BY RD_MAT, RD_FILIAL, RD_DATARQ