--Relação dos funcionários, dependentes e seus respectivos valores
SELECT RA_FILIAL, RA_MAT, 'TIT' AS TEMP, RA_NOME,
ISNULL((SELECT RD_VALOR FROM SRD010 C WHERE C.D_E_L_E_T_='' AND C.RD_DATARQ='201410' AND 
	RD_FILIAL=RA_FILIAL AND RD_MAT=RA_MAT AND RD_PD='C00'),'') AS 'VL_TIT', '' AS VL_DEP,
ISNULL((SELECT RD_HORAS FROM SRD010 C WHERE C.D_E_L_E_T_='' AND C.RD_DATARQ='201411' AND 
	RD_FILIAL=RA_FILIAL AND RD_MAT=RA_MAT AND RD_PD='900'),'') AS 'BS_EMP',
ISNULL((SELECT RD_VALOR FROM SRD010 C WHERE C.D_E_L_E_T_='' AND C.RD_DATARQ='201411' AND 
	RD_FILIAL=RA_FILIAL AND RD_MAT=RA_MAT AND RD_PD='900'),'') AS 'VL_EMP',
	RA_ASSMED_, Z03_DESC
FROM SRA010 A1
INNER JOIN Z03010 Z3 ON Z3.D_E_L_E_T_='' AND Z03_CODPLA=RA_ASSMED_
WHERE A1.D_E_L_E_T_='' AND RA_ASSMED_ <>'' AND RA_SITFOLH NOT IN ('D','T') ---and RA_FILIAL='001NE001' 
UNION ALL
SELECT RB_FILIAL, RB_MAT, B.RB_COD, B.RB_NOME, '' AS VL_TIT,
ISNULL((SELECT RD_VALOR FROM SRD010 C WHERE C.D_E_L_E_T_='' AND C.RD_DATARQ='201411' AND 
	RD_FILIAL=RA_FILIAL AND RD_MAT=RA_MAT AND SUBSTRING(RD_PD,1,1)='C' AND
	SUBSTRING(RD_PD,2,2)=B.RB_COD),'') AS 'VL_DEP', '' AS BS_EMP, '' AS VL_EMP, '' , ''
 FROM SRB010 B
INNER JOIN SRA010 A ON B.D_E_L_E_T_='' AND RA_FILIAL=RB_FILIAL AND RA_MAT=RB_MAT AND RB_ASSMED_='S'
 AND RA_ASSMED_ <>'' AND RA_SITFOLH NOT IN ('D','T')
--WHERE RA_FILIAL='001NE001'
ORDER BY 1,2,3 DESC

--Tabela de Assistências Médicas
SELECT Z03_CODPLA COD, Z03_DESC 'DESC', Z03_FORNEC FORNEC, SUBSTRING(RCC_CONTEU,4,30) FORNC_DESC, Z03_VLRPLA VLR_PLAN, Z03_VLRREF VLR_REF,  
(CASE Z03_DESCSO 
	WHEN '1' THEN 'VLR REF'
	WHEN '2' THEN 'SALARIO'
	WHEN '3' THEN 'VLR FIXO'
	WHEN '4' THEN 'FAIXAS'
	WHEN '5' THEN 'FX ETARIA'
	ELSE 'VAZIO' END) DESCONTO_SOB, Z03_PERCDE '% DESC', 
Z03_VLRDES 'VLR DESC', Z03_LIMDPE 'LIMITE DESC %', Z03_LIMDES 'LIMITE DESC VLR', 
(CASE Z03_PDDEPE 
	WHEN 'S' THEN 'SIM' 
	WHEN 'N' THEN 'NAO'
	ELSE 'VAZIO' END) 'DIF P/ DEP', Z03_PDEDEP '% DIF P/ DEP'
FROM Z03010 Z
INNER JOIN RCC010 R ON RCC_CODIGO='S016' AND RCC_SEQUEN=Z03_FORNEC AND R.D_E_L_E_T_='' AND Z.D_E_L_E_T_=''
