SELECT T.* FROM(
SELECT RA_FILIAL,RA_MAT,RA_NOME,RA_CATEG,RA_OCORREN,RA_SITFOLH,RA_AFASFGT,RA_RESCRAI,RA_DEMISSA,RA_ADMISSA,RA_TPCONTR
,ISNULL((SELECT SUM(RC_VALOR) FROM SRC010 WHERE D_E_L_E_T_ = '' AND
RC_FILIAL = RA_FILIAL AND RC_MAT = RA_MAT AND RC_PD IN
('701','702')),0) BASE_INSS
,ISNULL((SELECT SUM(RC_VALOR) FROM SRC010 WHERE D_E_L_E_T_ = '' AND
RC_FILIAL = RA_FILIAL AND RC_MAT = RA_MAT AND RC_PD IN
('503','501')),0) INSS_DESC
,ISNULL((SELECT SUM(RC_VALOR) FROM SRC010 WHERE D_E_L_E_T_ = '' AND
RC_FILIAL = RA_FILIAL AND RC_MAT = RA_MAT AND RC_PD IN
('703','704')),0) BASE_INSS13
,ISNULL((SELECT SUM(RC_VALOR) FROM SRC010 WHERE D_E_L_E_T_ = '' AND
RC_FILIAL = RA_FILIAL AND RC_MAT = RA_MAT AND RC_PD IN ('502')),0)
INSS_DESC_13
,ISNULL((SELECT SUM(RC_VALOR) FROM SRC010 WHERE D_E_L_E_T_ = '' AND
RC_FILIAL = RA_FILIAL AND RC_MAT = RA_MAT AND RC_PD IN ('764')),0)
BASE_FGTS
,ISNULL((SELECT SUM(RC_VALOR) FROM SRC010 WHERE D_E_L_E_T_ = '' AND
RC_FILIAL = RA_FILIAL AND RC_MAT = RA_MAT AND RC_PD IN ('765')),0)
FGTS
,ISNULL((SELECT SUM(RC_VALOR) FROM SRC010 WHERE D_E_L_E_T_ = '' AND
RC_FILIAL = RA_FILIAL AND RC_MAT = RA_MAT AND RC_PD IN ('766')),0)
BASE_FGTS13
,ISNULL((SELECT SUM(RC_VALOR) FROM SRC010 WHERE D_E_L_E_T_ = '' AND
RC_FILIAL = RA_FILIAL AND RC_MAT = RA_MAT AND RC_PD IN ('767')),0)
FGTS13
FROM SRA010
WHERE
D_E_L_E_T_ = ''
AND RA_FILIAL = '014NE008')T
WHERE BASE_FGTS > 0 OR BASE_FGTS13 > 0 OR BASE_INSS > 0 AND BASE_INSS13 > 0