SELECT * FROM (SELECT RA_FILIAL , RA_MAT,
		ISNULL((SELECT RC_VALOR FROM RC011312 WHERE D_E_L_E_T_ = ' ' AND RC_FILIAL = RA_FILIAL AND RC_MAT = RA_MAT AND RC_PD = '608'),0) RC608,
		ISNULL((SELECT RC_VALOR FROM RC011312 WHERE D_E_L_E_T_ = ' ' AND RC_FILIAL = RA_FILIAL AND RC_MAT = RA_MAT AND RC_PD = '653'),0) RC653,
		ISNULL((SELECT RI_VALOR FROM RI011313 WHERE D_E_L_E_T_ = ' ' AND RI_FILIAL = RA_FILIAL AND RI_MAT = RA_MAT AND RI_PD = '608'),0) RI608,
		ISNULL((SELECT RI_VALOR FROM RI011313 WHERE D_E_L_E_T_ = ' ' AND RI_FILIAL = RA_FILIAL AND RI_MAT = RA_MAT AND RI_PD = '653'),0) RI653
 FROM SRA010 A
  where A.D_E_L_E_T_ = ' ')T WHERE RC608>0 AND RI608 >0
  
  
  SELECT * FROM (SELECT RA_FILIAL , RA_MAT,
		ISNULL((SELECT TOP 1 RD_VALOR FROM SRD010 WHERE D_E_L_E_T_ = ' ' AND RD_FILIAL = RA_FILIAL AND RD_MAT = RA_MAT AND RD_PD = '608' AND RD_DATARQ >='201301'),0) RD608,
		ISNULL((SELECT SUM(RD_VALOR) FROM SRD010 WHERE D_E_L_E_T_ = ' ' AND RD_FILIAL = RA_FILIAL AND RD_MAT = RA_MAT AND RD_PD = '305' AND RD_DATARQ >='201301'),0) RD305
		FROM SRA010 A  where A.D_E_L_E_T_ = ' ')T WHERE RD608 > 0
  