SELECT T.* 
,(CASE WHEN AVOS_NOV = 0 AND RA_ADMISSA < '20131115' THEN 0 ELSE AVOS_NOV + 1 END) AVOS_PROJ
FROM(
SELECT RA_FILIAL,RA_MAT,RA_NOME,RA_ADMISSA,RA_SITFOLH,RA_CATFUNC,RA_SALARIO,RA_SALINCO,RA_INSMIN,RA_INSMED,RA_INSMAX,RA_PERICUL
,ISNULL((SELECT TOP 1 RT_AVOS13S FROM SRT010 WHERE RT_FILIAL = RA_FILIAL AND RT_MAT = RA_MAT AND RT_DATACAL = '20131130' AND D_E_L_E_T_ = '' AND RT_AVOS13S > 0),0) AVOS_NOV
,ISNULL((SELECT SUM(RI_VALOR) FROM SRI010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RI_FILIAL AND RA_MAT = RI_MAT AND RI_PD = '306'),0) VALOR_13S_VB306
,ISNULL((SELECT SUM(RI_VALOR) FROM SRI010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RI_FILIAL AND RA_MAT = RI_MAT AND RI_PD = '311'),0) VALOR_MEDIA_13S_VB311
,ISNULL((SELECT SUM(RI_VALOR) FROM SRI010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RI_FILIAL AND RA_MAT = RI_MAT AND RI_PD = '312'),0) VALOR_MEDIA_VR_13S_VB3312
,ISNULL((SELECT SUM(RI_VALOR) FROM SRI010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RI_FILIAL AND RA_MAT = RI_MAT AND RI_PD = '313'),0) VALOR_ISALUB_13S_VB313
,ISNULL((SELECT SUM(RI_VALOR) FROM SRI010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RI_FILIAL AND RA_MAT = RI_MAT AND RI_PD = '314'),0) VALOR_PERIC_13S_VB316
,ISNULL((SELECT SUM(RI_VALOR) FROM SRI010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RI_FILIAL AND RA_MAT = RI_MAT AND RI_PD = '608'),0) VALOR_DESADT_13S_VB608
,ISNULL((SELECT SUM(RD_VALOR) FROM SRD010 WHERE D_E_L_E_T_ = '' AND SUBSTRING(RD_DATARQ,1,4) = '2013' AND RA_FILIAL = RD_FILIAL AND RA_MAT = RD_MAT AND RD_PD = '305'),0) DESC_ACUMULADOS_305
FROM SRA010 A
WHERE 
    A.D_E_L_E_T_ = '' AND RA_SITFOLH <> 'D')T
ORDER BY 1,2    
