SELECT CON_NusTelefoneNumero_Resid,* FROM Contratados
WHERE CON_NusTelefoneNumero_Resid NOT IN ('NULL','')

--QRY para relacionar endereço com tipo
SELECT 
CASE WHEN UPPER(TEN_D1STIPOENDERECO) COLLATE SQL_Latin1_General_CP1_CI_AI = 'NENHUM' THEN 
	RA_ENDEREC 
ELSE UPPER(TEN_D1STIPOENDERECO)COLLATE SQL_Latin1_General_CP1_CI_AI
	+' '+RA_ENDEREC END RA_ENDEREC,
UPPER(TEN_D1STIPOENDERECO) COLLATE SQL_Latin1_General_CP1_CI_AI
 FROM [TOTVS_CMP].[dbo].[SRA_BSEND], Contratados, TiposEnderecos
WHERE CON_CdiContratado=RA_CRACHA AND TEN_CDITIPOENDERECO=CON_CdiTipoEndereco 
--AND (LEFT(RA_ENDEREC,3)='TRAV' OR LEFT(RA_ENDEREC,3)='AV.' OR  LEFT(RA_ENDEREC,3)='AV ' OR  LEFT(RA_ENDEREC,4)='RUA ')
/*
UPDATE [TOTVS_CMP].[dbo].[SRA_BSEND]
SET RA_ENDEREC = CASE WHEN UPPER(TEN_D1STIPOENDERECO) COLLATE SQL_Latin1_General_CP1_CI_AI = 'NENHUM' THEN A.RA_ENDEREC 
					ELSE UPPER(TEN_D1STIPOENDERECO)COLLATE SQL_Latin1_General_CP1_CI_AI +' '+A.RA_ENDEREC END
 FROM [TOTVS_CMP].[dbo].[SRA_BSEND] A, Contratados, TiposEnderecos
WHERE CON_CdiContratado=A.RA_CRACHA AND TEN_CDITIPOENDERECO=CON_CdiTipoEndereco 
AND (LEFT(A.RA_ENDEREC,3)<>'AV.' OR  LEFT(A.RA_ENDEREC,3)<>'AV ' OR  LEFT(A.RA_ENDEREC,4)<>'RUA ' OR LEFT(A.RA_ENDEREC,3)<>'TRAV')
*/

--QRY para relacionar numero do endereço com tipo
SELECT LEFT(CON_DssEnderecoNumero,6), RA_NUMENDE
 FROM [TOTVS_CMP].[dbo].[SRA_BSEND], Contratados, TiposEnderecos
WHERE CON_CdiContratado=RA_CRACHA AND TEN_CDITIPOENDERECO=CON_CdiTipoEndereco 
AND CON_DssEnderecoNumero NOT IN ('NULL','')
/*
UPDATE [TOTVS_CMP].[dbo].[SRA_BSEND]
SET RA_NUMENDE = LEFT(CON_DssEnderecoNumero,6)
 FROM [TOTVS_CMP].[dbo].[SRA_BSEND] A, Contratados, TiposEnderecos
WHERE CON_CdiContratado=RA_CRACHA AND TEN_CDITIPOENDERECO=CON_CdiTipoEndereco 
AND CON_DssEnderecoNumero NOT IN ('NULL','')

--AJUSTE DO TELEFONE
UPDATE [TOTVS_CMP].[dbo].[SRA_BSEND]
SET RA_TELEFON = CON_NusTelefoneNumero_Resid
 FROM [TOTVS_CMP].[dbo].[SRA_BSEND] A, Contratados, TiposEnderecos
WHERE CON_CdiContratado=RA_CRACHA AND TEN_CDITIPOENDERECO=CON_CdiTipoEndereco 
AND CON_NusTelefoneNumero_Resid NOT IN ('NULL','')

--AJUSTE DO DD
UPDATE [TOTVS_CMP].[dbo].[SRA_BSEND]
SET RA_DDDFONE = CON_CosTelefoneDDD_Resid
 FROM [TOTVS_CMP].[dbo].[SRA_BSEND] A, Contratados, TiposEnderecos
WHERE CON_CdiContratado=RA_CRACHA AND TEN_CDITIPOENDERECO=CON_CdiTipoEndereco 
AND CON_CosTelefoneDDD_Resid NOT IN ('NULL','')

*/


SELECT RA_ENDEREC,SUBSTRING(RA_ENDEREC,6,40),*  FROM [TOTVS_CMP].[dbo].[SRA_BSEND] 
WHERE RA_ENDEREC LIKE 'NI%'

UPDATE [TOTVS_CMP].[dbo].[SRA_BSEND] 
SET RA_ENDEREC = SUBSTRING(RA_ENDEREC,6,40)
WHERE RA_ENDEREC LIKE 'NIDA AV%'

SELECT RA_COMPLEM,*  FROM [TOTVS_CMP].[dbo].[SRA_BSEND]
WHERE RA_COMPLEM<>''