SELECT SRT.CVCODFIL, SRT.RT_MAT, SRT.RT_VERBA, SRT.DESCRI, 
 SRT.RT_TIPPROV, 
SRT.RT_HORAS, SRT.RT_VALOR, SRT.RT_DATACAL,
SRT.RT_CC, (CASE SRT.RT_VERBA WHEN '802' THEN SRF.RF_DATABAS ELSE '' END) AS RT_DATABASE, 
(CASE WHEN SRT.RT_VERBA = '802' AND SRT.RT_HORAS > '12' AND SRT.RT_TIPPROV = '1' THEN (((SRT.RT_HORAS-12))*2.5) ELSE '' END ) AS DFERANT,
(CASE WHEN SRT.RT_VERBA = '802' AND SRT.RT_HORAS < '12' THEN ((SRT.RT_HORAS-(SRT.RT_HORAS-12))*2.5) ELSE '' END ) AS DFERPRO
FROM SRTFULL SRT
INNER JOIN SRFTEMP SRF ON  SRF.RF_FILIAL = SRT.cvCodFil AND SRF.RF_MAT= SRT.RT_MAT AND SRF.D_E_L_E_T_=''
WHERE SRT.RT_MAT IN (SELECT RT_MAT FROM SRTTEMP)
GROUP BY SRT.CVCODFIL, SRT.RT_MAT, SRT.RT_VERBA, SRT.DESCRI, SRT.RT_TIPPROV, 
SRT.RT_HORAS, SRT.RT_VALOR, SRT.RT_DATACAL,SRT.RT_CC,  SRF.RF_DATABAS, 
(CASE WHEN SRT.RT_VERBA = '802' AND SRT.RT_HORAS < '12' THEN ((SRT.RT_HORAS-(SRT.RT_HORAS-12))*2.5) ELSE '999' END ),
(CASE WHEN SRT.RT_VERBA = '802' AND SRT.RT_HORAS > '12' THEN (((SRT.RT_HORAS-12))*2.5) ELSE '' END )
ORDER BY 1,2, 5,3


