--CONFORME CALCULO BUILDUP
SELECT NEW.RT_FILIAL, NEW.RT_MAT,
CASE WHEN OLD.RT_CC IS NOT NULL THEN OLD.RT_CC ELSE NEW.RT_CC END AS RT_CC, 
CASE WHEN OLD.RT_DATACAL IS NOT NULL THEN OLD.RT_DATACAL ELSE '20131231' END AS RT_DATACAL, 
 NEW.RT_TIPPROV,
	NEW.RT_VERBA, NEW.RT_VALOR, 
--OLD.RT_DATABAS, OLD.RT_DFERVEN, OLD.RT_DFERPRO, OLD.RT_SALARIO
ISNULL(OLD.RT_DATABAS,'') AS RT_DATABAS, 
CASE WHEN OLD.RT_DATABAS = '' THEN '' ELSE
SUBSTRING(OLD.RT_DATABAS,7,2)+'/'+SUBSTRING(OLD.RT_DATABAS,5,2)+'/'+SUBSTRING(OLD.RT_DATABAS,3,2) END,
ISNULL(OLD.RT_DFERVEN,'') AS RT_DFERVEN, 
ISNULL(OLD.RT_DFERPRO,'')AS RT_DFERPRO, ISNULL(OLD.RT_SALARIO,'') AS RT_SALARIO
FROM SRTBASE NEW
LEFT JOIN SRT990 OLD 
	ON OLD.RT_FILIAL = NEW.RT_FILIAL
AND	   OLD.RT_MAT	 = NEW.RT_MAT
AND	   OLD.RT_VERBA	 = NEW.RT_VERBA
AND	   OLD.RT_TIPPROV = NEW.RT_TIPPROV
--AND OLD.RT_MAT IN (SELECT TST.RT_MAT FROM SRT990 TST)
ORDER BY 2,1,5,6


SELECT * FROM SRT990