SELECT * FROM ConPeriodosDescansos
WHERE CPD_CdiContratado='100013800'

SELECT 
CASE WHEN CPI_DtdFimFerias_R IS NOT NULL THEN CPI_DtdFimFerias_R 
	WHEN CPI_DtdSaidaAbono_R IS NOT NULL THEN CPI_DtdSaidaAbono_R 
ELSE CPI_DtdSaidaLicenca_R END  RH_DATAFIM,
CPI_DtdFimFerias_R,
CPI_DtdSaidaAbono_R, CPI_QtnDiasFerias1_R, CPI_CdiStatusPeriodoItem,
CPI_DtdSaidaLicenca_R, CPI_CdiStatusPeriodoItem,
* FROM ConPeriodosDescansosIts
WHERE CPI_CdiConPeriodoDescanso='10879'

SELECT * INTO SRHCMPTEMP FROM (SELECT CPD_CdiContratado,
CONVERT(VARCHAR , CPD_DtdPeriodoInicio, 103 ) RH_DATABAS,
CONVERT(VARCHAR , CPD_DtdPeriodoFim, 103 ) RH_DBASEAT,
CONVERT(VARCHAR , CPI_DtdSaidaFerias_R, 103 ) RH_DATAINI, 
CONVERT(VARCHAR , (CASE WHEN CPI_DtdFimFerias_R IS NOT NULL THEN CPI_DtdFimFerias_R 
	WHEN CPI_DtdSaidaAbono_R IS NOT NULL THEN CPI_DtdSaidaAbono_R 
	WHEN CPI_DtdSaidaLicenca_R IS NOT NULL THEN CPI_DtdSaidaLicenca_R 
ELSE DATEADD (DAY , CPI_QtnDiasFerias_R-1, CPI_DtdSaidaFerias_R ) END),103) RH_DATAFIM,
CONVERT(VARCHAR , CPD_QtnDiasDireitoTotal, 103 ) RH_DFERVEN,
CPI_QtnDiasFerias_R RH_DFERIAS, CPI_QtnDiasAbono_R RH_DABONPE,
CONVERT(VARCHAR , (CASE WHEN CPI_DtdFeriasAviso_R IS NOT NULL THEN CPI_DtdFeriasAviso_R
ELSE DATEADD (MONTH , -1, CPI_DtdSaidaFerias_R )
END),103) RH_DTAVISO, 
CONVERT(VARCHAR , CPI_DtdDireitoPagto_R, 103 ) RH_DTRECIB,
CASE CPI_Opl13Salario_R WHEN 1 THEN 50 ELSE 0 END RH_PER13S,
CASE CPI_CdiModoDescanso_R WHEN 2 THEN 'COLETIVA' ELSE '' END RH_OBSERV,
CPD_QtnFaltasInjustificadas RH_DFALTAS,
CPI_CdiConPeriodoDescanso
FROM ConPeriodosDescansosIts
INNER JOIN ConPeriodosDescansos ON CPI_CdiConPeriodoDescanso = CPD_CdiConPeriodoDescanso
--AND CPI_CdiConPeriodoDescanso='12347'
--AND CPD_CdiContratado='800001060'
AND CPD_CdiStatusPeriodo IN ('2','3') AND CPI_CdiStatusPeriodoItem <> '8'
)T

 SELECT RA_FILIAL, RA_MAT,* FROM [apcmp].[dbo].[SRHCMPTEMP] B
INNER JOIN [TOTVS_CMP].[dbo].[SRA990] A ON A.RA_CRACHA=B.CPD_CdiContratado
WHERE CPD_CdiContratado='100013520'

SELECT * FROM SRHCMP22 A, SRH0101 B
WHERE A.RH_FILIAL+A.RH_MAT+A.RH_DATABAS+A.RH_DATAINI = B.RH_FILIAL+B.RH_MAT+B.RH_DATABAS+B.RH_DATAINI

DELETE SRHCMP22
WHERE RH_FILIAL+RH_MAT+RH_DATABAS+RH_DATAINI IN 
(
SELECT  B.RH_FILIAL+B.RH_MAT+B.RH_DATABAS+B.RH_DATAINI FROM SRH0101 B
)


SELECT A.CPD_CdiContratado,A.RH_DATABAS,A.RH_DBASEAT,A.RH_DATAINI, COUNT(*) FROM SRHCMPTEMP A
GROUP BY A.CPD_CdiContratado,A.RH_DATABAS,A.RH_DBASEAT,A.RH_DATAINI
having COUNT(*) > 1
ORDER BY 4 DESC

SELECT * FROM SRHCMP22
WHERE RH_FILIAL+RH_MAT='05801060'

SELECT RA_CRACHA,RA_ADMISSA,RA_DEMISSA,* FROM SRA990
WHERE RA_MAT='006797' AND 
RA_CRACHA='100013881'


DELETE [SRHCMPTEMP]
WHERE CPD_CdiContratado='100013520'
AND CPI_CdiConPeriodoDescanso='1912' AND RH_PER13S<>50

DROP TABLE SRHCMPTEMP

 SELECT * INTO SRHFALTA FROM (SELECT * FROM [apcmp].[dbo].[SRHCMPTEMP] B
INNER JOIN [TOTVS_CMP].[dbo].[SRA990] A ON A.RA_CRACHA=B.CPD_CdiContratado)T

SELECT * FROM SRJ990
ORDER BY 2