select RA_FILIAL, RA_MAT, rtrim(RA_NOME), RA_CIC, RJ_DESC, RJ_XBIVEL, RD_PD, RD_VALOR, RA_CODFUNC 
FROM SRA010 A, SRD010 B, SRJ010 C
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND RA_FILIAL = RD_FILIAL
AND RA_MAT = RD_MAT
AND RA_CODFUNC = RJ_FUNCAO
AND RD_DATARQ = '201311'
AND RD_PD = '999'
and RA_FILIAL = '022NE002'

SELECT * FROM SRJ010
SELECT RA_FILIAL,RA_MAT,RTRIM(RA_NOME),RA_CIC,RA_ADMISSA,RJ_DESC,RA_CC, CTT_DESC01
FROM SRA010 A, SRJ010 B, CTT010 C
WHERE
A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = '' 
AND RA_SITFOLH <> 'D'
AND RA_ADMISSA >= '20130101'
AND RA_CODFUNC = RJ_FUNCAO
AND RA_CC = CTT_CUSTO


select * from SRA010 WHERE D_E_L_E_T_ = ' '
AND RA_SITFOLH <> 'D'
AND RA_CC = '070010007'