select * from SRA010 WHERE D_E_L_E_T_ = ' '
AND RA_NOME LIKE 'ANA LUCIA MORETTI'

SELECT RA_FILIAL, RA_MAT, RA_NOME, RA_CIC, RA_PIS, RC_PD, RV_DESC, RC_VALOR
FROM SRA010 A, SRC010 B, SRV010 C
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND RA_FILIAL = RC_FILIAL
AND RA_MAT = RC_MAT
AND RC_PD = RV_COD
AND RA_CATFUNC = 'A'
and RC_PD IN ('200','501','509','510','999')
ORDER BY RA_FILIAL, RA_MAT

SELECT RA_FILIAL, RA_MAT, RA_NOME, RA_CIC, RA_PIS, RD_PD, RV_DESC, RD_VALOR, RD_DATARQ
FROM SRA010 A, SRD010 B, SRV010 C
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND RA_FILIAL = RD_FILIAL
AND RA_MAT = RD_MAT
AND RD_PD = RV_COD
AND RA_CATFUNC = 'A'
and RD_PD = '999'--IN ('200','501','509','510')
AND RD_DATARQ = '201405'
ORDER BY RA_FILIAL, RA_MAT


SELECT * FROM SRC010 WHERE RC_PD = '720'

SELECT * FROM SRD010 WHERE RD_DATARQ = '201307' AND RD_PD = '720'

SELECT * FROM SRA010 WHERE D_E_L_E_T_ = ' ' AND RA_NOME LIKE 'BRENO CALEIRO PALMA'

select RA_FILIAL, RA_MAT, RA_NOME, RA_CIC, RA_BCDEPSA, RA_CTDEPSA
FROM SRA010 WHERE D_E_L_E_T_ = ' '
AND RA_CATFUNC = 'A'
