SELECT RA_FILIAL, RA_MAT, RTRIM(RA_NOME), RA_NASC, RA_CIC, RA_CC, RA_SITFOLH, RA_ASSMED_,RA_ASSODO_
FROM SRA010 WHERE D_E_L_E_T_ = ' '
and RA_SITFOLH <> 'D'


SELECT RB_FILIAL, RB_MAT, RB_COD, RTRIM(RB_NOME), RB_DTNASC, RB_SEXO, RB_GRAUPAR, RB_CIC, RB_ASSMED_, RB_ASSODO_
FROM SRB010 WHERE D_E_L_E_T_ = ' ' 

select RA_FILIAL,RA_MAT,RTRIM(RA_NOME),RA_CIC,RA_CC,RD_PD,RV_DESC,RD_HORAS,RD_VALOR,RD_DATARQ
from SRA010 A,SRD010 B, SRV010 C
where RA_FILIAL = RD_FILIAL 
and RA_MAT = RD_MAT 
and RD_PD = RV_COD 
and RD_PD in ('550','560','562') 
and RD_DATARQ = '201308'
and RD_VALOR <> '0'
and A.D_E_L_E_T_ = ' '
and B.D_E_L_E_T_ = ' '
and C.D_E_L_E_T_ = ' '
