SELECT W.* FROM(
SELECT T.* 
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD = '058'),0),2) PERIC
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('048','049','050')),0),2) INSALUB
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD = '765'),0),2) FGTS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('713','714','715')),0),2) INSS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('953')),0),2) PROV_13SAL
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('955')),0),2) PROV_FGTS_13SAL
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('954')),0),2) PROV_INSS_13SAL
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('950','960','961')),0),2) PROV_FERIAS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('952')),0),2) PROV_FERIAS_FGTS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('951')),0),2) PROV_FERIAS_INSS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('900')),0),2) ASS_MED_EMPRESA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('B09')),0),2) ASS_ODO_EMPRESA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('831')),0),2) SEGURO_VIDA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('872')),0),2) VT_EMPRESA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('871')),0),2) REFEICAO_EMPRESA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('870')),0),2) ALIMENTACAO_EMPRESA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('123','130','131','132','133','134','135','136','137','141','142','143','144','145','146','147','148')),0),2) HORAS_EXTRAS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('090','091','092','093','094','095','096')),0)+RA_SALARIO,2)  SALARIO_INCORP
FROM(
SELECT RA_FILIAL,RA_CC CC,CTT_DESC01,RA_MAT,RA_NOME,RJ_DESC,RA_SALARIO
FROM SRA010 A, CTT010 B, SRJ010 C
WHERE
    A.D_E_L_E_T_ = '' AND B.D_E_L_E_T_ = '' AND C.D_E_L_E_T_ = ' 'AND CTT_CUSTO = RA_CC AND RA_CODFUNC = RJ_FUNCAO
    AND SUBSTRING(RA_FILIAL,1,3) IN ('002','003'))T)W
WHERE PERIC+FGTS+INSS+PROV_13SAL+PROV_FGTS_13SAL+PROV_INSS_13SAL+PROV_FERIAS_FGTS+PROV_FERIAS_INSS+ASS_MED_EMPRESA+ASS_ODO_EMPRESA+SEGURO_VIDA+VT_EMPRESA+REFEICAO_EMPRESA+ALIMENTACAO_EMPRESA > 0
ORDER BY RA_FILIAL,RA_MAT



SELECT W.* FROM(
SELECT T.* 
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD = '058'),0),2) PERIC
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('048','049','050')),0),2) INSALUB
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD = '765'),0),2) FGTS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('713','714','715')),0),2) INSS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('953')),0),2) PROV_13SAL
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('955')),0),2) PROV_FGTS_13SAL
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('954')),0),2) PROV_INSS_13SAL
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('950','960','961')),0),2) PROV_FERIAS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('952')),0),2) PROV_FERIAS_FGTS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('951')),0),2) PROV_FERIAS_INSS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('900')),0),2) ASS_MED_EMPRESA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('B09')),0),2) ASS_ODO_EMPRESA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('831')),0),2) SEGURO_VIDA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('872')),0),2) VT_EMPRESA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('871')),0),2) REFEICAO_EMPRESA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('870')),0),2) ALIMENTACAO_EMPRESA
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('123','130','131','132','133','134','135','136','137','141','142','143','144','145','146','147','148')),0),2) HORAS_EXTRAS
,ROUND(ISNULL((SELECT SUM(RZ_VAL) FROM SRZ010 WHERE D_E_L_E_T_ = '' AND RA_FILIAL = RZ_FILIAL AND RA_MAT = RZ_MAT AND RZ_CC = CC AND RZ_PD IN ('090','091','092','093','094','095','096')),0)+RA_SALARIO,2)  SALARIO_INCORP
FROM(
SELECT RA_FILIAL,RA_CC CC,CTT_DESC01,RA_MAT,RA_NOME,RJ_DESC,RA_SALARIO
FROM SRA010 A, CTT010 B, SRJ010 C
WHERE
    A.D_E_L_E_T_ = '' AND B.D_E_L_E_T_ = '' AND C.D_E_L_E_T_ = ' 'AND CTT_CUSTO = RA_CC AND RA_CODFUNC = RJ_FUNCAO
    AND SUBSTRING(RA_CC,1,2) = '03')T)W
WHERE PERIC+FGTS+INSS+PROV_13SAL+PROV_FGTS_13SAL+PROV_INSS_13SAL+PROV_FERIAS_FGTS+PROV_FERIAS_INSS+ASS_MED_EMPRESA+ASS_ODO_EMPRESA+SEGURO_VIDA+VT_EMPRESA+REFEICAO_EMPRESA+ALIMENTACAO_EMPRESA > 0
ORDER BY RA_FILIAL,RA_MAT
