SELECT RV_INSS, RV_IR, RV_FGTS, RV_MED13, RV_MEDFER, RV_MEDAVI * FROM SRV010
WHERE RV_REFSRVD <> ''
ORDER BY 2

--UPDATE SRV010
--SET RV_DESCDET = 'Historico Ficha Financeira APDATA'
--WHERE RV_REFSRVD <> ''

SELECT A.RV_COD, A.RV_REFSRVD, A.RV_DESC, A.RV_INSS, A.RV_IR, A.RV_FGTS, A.RV_MED13, A.RV_MEDFER, A.RV_MEDAVI
,B.RV_COD, B.RV_REFSRVD,B.RV_DESC, B.RV_INSS, B.RV_IR, B.RV_FGTS, B.RV_MED13, B.RV_MEDFER, B.RV_MEDAVI
 FROM SRV010 A, SRV010 B
WHERE A.RV_REFSRVD <> '' AND A.RV_REFSRVD=B.RV_COD AND A.RV_REFSRVD<>'000'
ORDER BY 2

--RV_INSS, RV_IR, RV_FGTS, RV_MED13, RV_MEDFER, RV_MEDAVI

BEGIN TRANSACTION 
UPDATE 
	SRV010
SET	
SRV010.RV_INSS = T2.RV_INSS, 
SRV010.RV_IR = T2.RV_IR, 
SRV010.RV_FGTS = T2.RV_FGTS, 
SRV010.RV_MED13 = T2.RV_MED13, 
SRV010.RV_MEDFER = T2.RV_MEDFER, 
SRV010.RV_MEDAVI = T2.RV_MEDAVI,
SRV010.RV_INCORP = T2.RV_INCORP,
SRV010.RV_REF13 = T2.RV_REF13,
SRV010.RV_REFFER = T2.RV_REFFER,
SRV010.RV_ADIANTA = T2.RV_ADIANTA,
SRV010.RV_PERICUL = T2.RV_PERICUL,
SRV010.RV_INSALUB = T2.RV_INSALUB,
SRV010.RV_PENSAO = T2.RV_PENSAO,
SRV010.RV_DSRHE = T2.RV_DSRHE,
SRV010.RV_HE = T2.RV_HE,
SRV010.RV_ADICTS = T2.RV_ADICTS,
SRV010.RV_SINDICA = T2.RV_SINDICA,
SRV010.RV_SALFAMI = T2.RV_SALFAMI,
SRV010.RV_SEGVIDA = T2.RV_SEGVIDA,
SRV010.RV_DEDINSS = T2.RV_DEDINSS,
SRV010.RV_TIPO = T2.RV_TIPO,
SRV010.RV_TIPOCOD = T2.RV_TIPOCOD,
SRV010.RV_PERC = T2.RV_PERC, 
SRV010.RV_RAIS = T2.RV_RAIS, 
SRV010.RV_DIRF = T2.RV_DIRF, 
SRV010.RV_COMPL_ = T2.RV_COMPL_
FROM
	SRV010 INNER JOIN 
	SRV010 AS T2 ON SRV010.RV_REFSRVD=T2.RV_COD
WHERE SRV010.RV_REFSRVD <> '' AND SRV010.RV_REFSRVD<>'000'

--ROLLBACK WORK;
--COMMIT;
