	SELECT * FROM PCC_SE5 
 UNION ALL		
 SELECT DISTINCT 
 E1_FILIAL,  	
 E1_EMISSAO,  	
	E1_PREFIXO,  	
	E1_NUM,  		
	E1_CLIENTE,  	
	E1_LOJA,  		
	A1_NOME, 		
	A1_CGC, 		
	F2_VALBRUT, 	
	E1_VALOR, 		
	TIT_PIS_VAL = CASE WHEN (SELECT E1_VALOR FROM  SE1010 IE1 WHERE IE1.D_E_L_E_T_='' AND IE1.E1_FILIAL = E1.E1_FILIAL AND  IE1.E1_TIPO IN ('PI-','PIS') AND IE1.E1_PREFIXO = E1.E1_PREFIXO AND IE1.E1_NUM = E1.E1_NUM AND IE1.E1_CLIENTE = E1.E1_CLIENTE AND IE1.E1_PARCELA = E1.E1_PARCELA) IS NULL
		THEN (SELECT E5_VRETPIS FROM  SE5010 IE5 WHERE IE5.D_E_L_E_T_='' AND IE5.E5_FILIAL = E1.E1_FILIAL AND  IE5.E5_PREFIXO = E1.E1_PREFIXO AND IE5.E5_NUMERO = E1.E1_NUM AND IE5.E5_CLIENTE = E1.E1_CLIENTE AND IE5.E5_PARCELA = E1.E1_PARCELA 
			AND (E5_MOTBX NOT IN ('PIS','CSL','COF','PI-','CS-','CF-') AND E5_VRETPIS<>0))
		ELSE (SELECT E1_VALOR FROM  SE1010 IE1 WHERE IE1.D_E_L_E_T_='' AND IE1.E1_FILIAL = E1.E1_FILIAL AND  IE1.E1_TIPO IN ('PI-','PIS') AND IE1.E1_PREFIXO = E1.E1_PREFIXO AND IE1.E1_NUM = E1.E1_NUM AND IE1.E1_CLIENTE = E1.E1_CLIENTE AND IE1.E1_PARCELA = E1.E1_PARCELA)
		END, 
	TIT_COF_VAL = CASE WHEN (SELECT E1_VALOR FROM  SE1010 IE1 WHERE IE1.D_E_L_E_T_='' AND IE1.E1_FILIAL = E1.E1_FILIAL AND  IE1.E1_TIPO IN ('CF-','COF') AND IE1.E1_PREFIXO = E1.E1_PREFIXO AND IE1.E1_NUM = E1.E1_NUM AND IE1.E1_CLIENTE = E1.E1_CLIENTE AND IE1.E1_PARCELA = E1.E1_PARCELA) IS NULL
		THEN (SELECT E5_VRETCOF FROM  SE5010 IE5 WHERE IE5.D_E_L_E_T_='' AND IE5.E5_FILIAL = E1.E1_FILIAL AND  IE5.E5_PREFIXO = E1.E1_PREFIXO AND IE5.E5_NUMERO = E1.E1_NUM AND IE5.E5_CLIENTE = E1.E1_CLIENTE AND IE5.E5_PARCELA = E1.E1_PARCELA
			AND (E5_MOTBX NOT IN ('PIS','CSL','COF','PI-','CS-','CF-') AND E5_VRETCOF<>0))
		ELSE (SELECT E1_VALOR FROM  SE1010 IE1 WHERE IE1.D_E_L_E_T_='' AND IE1.E1_FILIAL = E1.E1_FILIAL AND  IE1.E1_TIPO IN ('CF-','COF') AND IE1.E1_PREFIXO = E1.E1_PREFIXO AND IE1.E1_NUM = E1.E1_NUM AND IE1.E1_CLIENTE = E1.E1_CLIENTE AND IE1.E1_PARCELA = E1.E1_PARCELA)
		END, 
	TIT_CSLL_VAL = CASE WHEN (SELECT E1_VALOR FROM  SE1010 IE1 WHERE IE1.D_E_L_E_T_='' AND IE1.E1_FILIAL = E1.E1_FILIAL AND  IE1.E1_TIPO IN ('CS-','CSL') AND IE1.E1_PREFIXO = E1.E1_PREFIXO AND IE1.E1_NUM = E1.E1_NUM AND IE1.E1_CLIENTE = E1.E1_CLIENTE AND IE1.E1_PARCELA = E1.E1_PARCELA) IS NULL
		THEN (SELECT E5_VRETCSL FROM  SE5010 IE5 WHERE IE5.D_E_L_E_T_='' AND IE5.E5_FILIAL = E1.E1_FILIAL AND  IE5.E5_PREFIXO = E1.E1_PREFIXO AND IE5.E5_NUMERO = E1.E1_NUM AND IE5.E5_CLIENTE = E1.E1_CLIENTE AND IE5.E5_PARCELA = E1.E1_PARCELA
			AND (E5_MOTBX NOT IN ('PIS','CSL','COF','PI-','CS-','CF-') AND E5_VRETCSL<>0))
		ELSE (SELECT E1_VALOR FROM  SE1010 IE1 WHERE IE1.D_E_L_E_T_='' AND IE1.E1_FILIAL = E1.E1_FILIAL AND  IE1.E1_TIPO IN ('CS-','CSL') AND IE1.E1_PREFIXO = E1.E1_PREFIXO AND IE1.E1_NUM = E1.E1_NUM AND IE1.E1_CLIENTE = E1.E1_CLIENTE AND IE1.E1_PARCELA = E1.E1_PARCELA)
		END,  
	E1.E1_BAIXA,
 E1.E1_NATUREZ, 
 ORIG = 'SE1', E1.E1_PARCELA  
 FROM SE1010 E1 WITH(NOLOCK)  
	INNER JOIN SA1010 A1 WITH(NOLOCK)  
		ON A1.D_E_L_E_T_='' 	
		AND E1_CLIENTE = A1_COD 
		AND E1_LOJA = A1_LOJA  	
	INNER JOIN SF2010 F2 WITH(NOLOCK)  
		ON F2.D_E_L_E_T_='' 	
		AND E1_FILIAL = F2_FILIAL  
		AND E1_PREFIXO = F2_PREFIXO  
		AND E1_NUM = F2_DOC  		
		AND E1_CLIENTE = F2_CLIENTE 
		AND E1_LOJA = F2_LOJA  		
 WHERE E1.D_E_L_E_T_=''   		
 AND E1_TIPO = 'NF'  			
	AND E1_FILIAL BETWEEN  '         ' AND '001NE001 ' 
	AND E1_CLIENTE BETWEEN  '' AND 'ZZZZZZ' 
	AND E1_LOJA BETWEEN  '' AND 'ZZ' 
	AND E1_BAIXA BETWEEN  '20140701' AND '20140915' 
	AND (((((((((SELECT IE1.E1_VALOR FROM SE1010 IE1 WITH(NOLOCK) WHERE IE1.D_E_L_E_T_='' AND IE1.E1_FILIAL = E1.E1_FILIAL AND  IE1.E1_PREFIXO = E1.E1_PREFIXO 
			AND IE1.E1_NUM = E1.E1_NUM AND IE1.E1_CLIENTE = E1.E1_CLIENTE AND IE1.E1_LOJA = E1.E1_LOJA AND IE1.E1_TIPO IN ('PI-','PIS') AND IE1.E1_PARCELA = E1.E1_PARCELA) IS NOT NULL ))
		OR (SELECT E5_VRETPIS FROM  SE5010 IE5 WHERE IE5.D_E_L_E_T_='' AND IE5.E5_FILIAL = E1.E1_FILIAL AND  IE5.E5_PREFIXO = E1.E1_PREFIXO 
			AND IE5.E5_NUMERO = E1.E1_NUM AND IE5.E5_CLIENTE = E1.E1_CLIENTE AND IE5.E5_PARCELA = E1.E1_PARCELA AND (E5_MOTBX NOT IN ('PIS','CSL','COF','PI-','CS-','CF-') AND E5_VRETPIS<>0)) IS NOT NULL))
		OR (SELECT IE1.E1_VALOR FROM SE1010 IE1 WITH(NOLOCK) WHERE IE1.D_E_L_E_T_='' AND IE1.E1_FILIAL = E1.E1_FILIAL AND  IE1.E1_PREFIXO = E1.E1_PREFIXO 
			AND IE1.E1_NUM = E1.E1_NUM AND IE1.E1_CLIENTE = E1.E1_CLIENTE AND IE1.E1_LOJA = E1.E1_LOJA AND IE1.E1_TIPO IN ('CS-','CSL') AND IE1.E1_PARCELA = E1.E1_PARCELA) IS NOT NULL 
		OR (SELECT E5_VRETCOF FROM  SE5010 IE5 WHERE IE5.D_E_L_E_T_='' AND IE5.E5_FILIAL = E1.E1_FILIAL AND  IE5.E5_PREFIXO = E1.E1_PREFIXO
			AND IE5.E5_NUMERO = E1.E1_NUM AND IE5.E5_CLIENTE = E1.E1_CLIENTE AND IE5.E5_PARCELA = E1.E1_PARCELA AND (E5_MOTBX NOT IN ('PIS','CSL','COF','PI-','CS-','CF-') AND E5_VRETCOF<>0)) IS NOT NULL))
		OR (SELECT IE1.E1_VALOR FROM SE1010 IE1 WITH(NOLOCK) WHERE IE1.D_E_L_E_T_='' AND IE1.E1_FILIAL = E1.E1_FILIAL AND  IE1.E1_PREFIXO = E1.E1_PREFIXO 
			AND IE1.E1_NUM = E1.E1_NUM AND IE1.E1_CLIENTE = E1.E1_CLIENTE AND IE1.E1_LOJA = E1.E1_LOJA AND IE1.E1_TIPO IN ('CF-','COF') AND IE1.E1_PARCELA = E1.E1_PARCELA) IS NOT NULL
		OR (SELECT E5_VRETCSL FROM  SE5010 IE5 WHERE IE5.D_E_L_E_T_='' AND IE5.E5_FILIAL = E1.E1_FILIAL AND  IE5.E5_PREFIXO = E1.E1_PREFIXO 
			AND IE5.E5_NUMERO = E1.E1_NUM AND IE5.E5_CLIENTE = E1.E1_CLIENTE AND IE5.E5_PARCELA = E1.E1_PARCELA AND (E5_MOTBX NOT IN ('PIS','CSL','COF','PI-','CS-','CF-') AND E5_VRETCSL<>0)) IS NOT NULL))


