SELECT																							
SUBSTRING(CT2_FILIAL,1,5) AS EMPRESA, CT2_FILIAL, CT2_DEBITO AS CONTA, SUBSTRING(CT2_FILIAL,1,5)+CT2_DEBITO AS FILEMP, RTRIM(CT2_FILIAL+CT2_DEBITO) AS FIlCONTA,		
TIPO = 'D', SUBSTRING(CT2_DATA,1,4) AS REF, CAST(SUM(CASE WHEN CT2_DC = '2' THEN '0' ELSE CT2_VALOR END)AS NUMERIC(12,2)) AS VALOR		
FROM CT1010 CT1                                                                                              		
INNER JOIN CT2010 CT2 ON CT2.CT2_DEBITO=CT1.CT1_CONTA																
WHERE CT1.D_E_L_E_T_='' AND CT1.CT1_CLASSE='2'                                                                       
AND CT2_DATA BETWEEN '20110101' AND '20131231'																		
AND (CT2_FILIAL) = '001NE001'																				
AND CT2_DEBITO<>''
GROUP BY CT2_FILIAL, CT2_DEBITO,SUBSTRING(CT2_DATA,1,4)
UNION ALL
SELECT 
SUBSTRING(CT2_FILIAL,1,5) AS EMPRESA, CT2_FILIAL, CT2_CREDIT AS CONTA, SUBSTRING(CT2_FILIAL,1,5)+CT2_CREDIT AS FILEMP, RTRIM(CT2_FILIAL+CT2_CREDIT) AS FILCONTA,		
TIPO = 'C', SUBSTRING(CT2_DATA,1,4) AS REF, CAST(SUM(CASE WHEN CT2_DC = '2' THEN '0' ELSE CT2_VALOR END)AS NUMERIC(12,2))*(-1) AS VALOR
FROM CT2010
WHERE D_E_L_E_T_=''
AND CT2_DATA BETWEEN '20110101' AND '20131231'
AND (CT2_FILIAL) = '001NE001'
AND CT2_CREDIT <>''
GROUP BY CT2_FILIAL, CT2_CREDIT,SUBSTRING(CT2_DATA,1,4)
UNION ALL
SELECT																							
SUBSTRING(CT2_FILIAL,1,5) AS EMPRESA, CT2_FILIAL, CT2_DEBITO AS CONTA, SUBSTRING(CT2_FILIAL,1,5)+CT2_DEBITO AS FILEMP, RTRIM(CT2_FILIAL+CT2_DEBITO) AS FIlCONTA,		
TIPO = 'D', SUBSTRING(CT2_DATA,1,6) AS REF, CAST(SUM(CASE WHEN CT2_DC = '2' THEN '0' ELSE CT2_VALOR END)AS NUMERIC(12,2)) AS VALOR		
FROM CT1010 CT1                                                                                              		
INNER JOIN CT2010 CT2 ON CT2.CT2_DEBITO=CT1.CT1_CONTA																
WHERE CT1.D_E_L_E_T_='' AND CT1.CT1_CLASSE='2'                                                                       
AND CT2_DATA BETWEEN '20140101' AND '20140131'																		
AND (CT2_FILIAL) = '001NE001'																				
AND CT2_DEBITO<>''
GROUP BY CT2_FILIAL, CT2_DEBITO,
SUBSTRING(CT2_DATA,1,6)
UNION ALL
SELECT 
SUBSTRING(CT2_FILIAL,1,5) AS EMPRESA, CT2_FILIAL, CT2_CREDIT AS CONTA, SUBSTRING(CT2_FILIAL,1,5)+CT2_CREDIT AS FILEMP, RTRIM(CT2_FILIAL+CT2_CREDIT) AS FILCONTA,		
TIPO = 'C', SUBSTRING(CT2_DATA,1,6) AS REF, CAST(SUM(CASE WHEN CT2_DC = '2' THEN '0' ELSE CT2_VALOR END)AS NUMERIC(12,2))*(-1) AS VALOR
FROM CT2010
WHERE D_E_L_E_T_=''
AND CT2_DATA BETWEEN '20140101' AND '20140331'
AND (CT2_FILIAL) = '001NE001'
AND CT2_CREDIT <>''
GROUP BY CT2_FILIAL, CT2_CREDIT,SUBSTRING(CT2_DATA,1,6)
ORDER BY 2,3,7