 SELECT 
 E1_FILIAL,  
 E1_EMISSAO,  
 E1_PREFIXO,  
 E1_NUM,  
 E1_CLIENTE,  
 E1_LOJA,  
 A1_NOME, 
 A1_CGC, 
 F2_VALBRUT, 
 E1_VALOR, 
 CASE E5_MOTBX 
 	WHEN 'PIS' THEN E5_VALOR 
 	WHEN 'CSL' THEN 0 
 	WHEN 'COF' THEN 0 
 END AS TIT_PIS_VAL, 
 CASE E5_MOTBX 
 	WHEN 'PIS' THEN 0 
 	WHEN 'CSL' THEN 0 
 	WHEN 'COF' THEN E5_VALOR 
 END AS TIT_COF_VAL, 
 CASE E5_MOTBX 
 	WHEN 'PIS' THEN 0 
 	WHEN 'CSL' THEN E5_VALOR 
 	WHEN 'COF' THEN 0 
 END AS TIT_CSLL_VAL, 
 E1.E1_BAIXA,  
 E1.E1_NATUREZ,  
 ORIG = 'SE5', E1.E1_PARCELA  
 INTO PCC_01 
 FROM SE1010 E1 WITH(NOLOCK) 
 	INNER JOIN SA1010 A1  
 		ON A1.D_E_L_E_T_='' 
 		AND E1_CLIENTE = A1_COD  
 		AND E1_LOJA = A1_LOJA 
 	INNER JOIN SF2010 F2 WITH(NOLOCK) 
 		ON F2.D_E_L_E_T_='' 
 		AND E1_FILIAL = F2_FILIAL  
 		AND E1_PREFIXO = F2_SERIE  
 		AND E1_NUM = F2_DOC  
 		AND E1_CLIENTE = F2_CLIENTE  
 		AND E1_LOJA = F2_LOJA  
 	INNER JOIN SE5010 E5 WITH(NOLOCK) 
 		ON E5.D_E_L_E_T_=''  
 		AND E5_FILIAL = E1_FILIAL  
 		AND E1_PREFIXO = E5_PREFIXO  
 		AND E1_NUM = E5_NUMERO  
 		AND E1_CLIENTE = E5_CLIENTE  
 		AND E1_LOJA = E5_LOJA  
 		AND E1_PARCELA = E5_PARCELA  
 		AND E5_TIPO = E1_TIPO  
 		AND E5_MOTBX IN ('PIS','CSL','COF') 
 WHERE E1.D_E_L_E_T_=''   
 AND E1_TIPO = 'NF'  
	AND E1_FILIAL BETWEEN  '         ' AND '001NE001 ' 
	AND E1_CLIENTE BETWEEN  '' AND 'ZZZZZZ' 
	AND E1_LOJA BETWEEN  '' AND 'ZZ' 
	AND E5_DTDISPO BETWEEN  '20140701' AND '20140915' 
 AND E5_MOTBX IN ('PIS','CSL','COF') 
 ORDER BY 1,2,3,4 