

--ANALITICO
select RZ_FILIAL, RZ_MAT, RA_CC, RZ_PD, RV_DESC, RZ_VAL, CTT_DESC01, CTT_TPCCDC,(CASE WHEN CTT_TPCCDC = 'C' THEN RV_XDEBCUS ELSE RV_XDEBDES END) CTA_DEBITO,(CASE WHEN CTT_TPCCDC = 'C' THEN RV_XCRECUS ELSE RV_XCREDES END) CTA_CREDITO 
from SRZ010 A, SRV010 B, SRA010 C, CTT010 D
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND D.D_E_L_E_T_ = ' '
AND RA_FILIAL = RZ_FILIAL
AND RA_MAT = RZ_MAT
AND RZ_PD = RV_COD
AND RA_CC = CTT_CUSTO
AND SUBSTRING(RZ_FILIAL,1,3) IN  ('022','023','024')


--SINTETICO

SELECT RZ_FILIAL, RA_CC, CTT_DESC01, RZ_PD, RV_DESC,  CTT_TPCCDC,CTA_DEBITO, CTA_CREDITO, SUM(RZ_VAL) FROM (
select RZ_FILIAL, RZ_MAT, RA_CC, RZ_PD, RV_DESC, RZ_VAL, CTT_DESC01, CTT_TPCCDC,(CASE WHEN CTT_TPCCDC = 'C' THEN RV_XDEBCUS ELSE RV_XDEBDES END) CTA_DEBITO,(CASE WHEN CTT_TPCCDC = 'C' THEN RV_XCRECUS ELSE RV_XCREDES END) CTA_CREDITO 
from SRZ010 A, SRV010 B, SRA010 C, CTT010 D
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND D.D_E_L_E_T_ = ' '
AND RA_FILIAL = RZ_FILIAL
AND RA_MAT = RZ_MAT
AND RZ_PD = RV_COD
AND RA_CC = CTT_CUSTO
AND RV_LCTOP <> ' '
AND SUBSTRING(RZ_FILIAL,1,3) IN  ('022','023','024')
)T
GROUP BY RZ_FILIAL, RA_CC, CTT_DESC01, RZ_PD, RV_DESC,  CTT_TPCCDC,CTA_DEBITO, CTA_CREDITO



SELECT * FROM CT5010 WHERE CT5_LANPAD = 'X01'