/*
Listas de empregados Ativos e lista de Desligados contendo os seguintes campos:
 Nome, PIS, Função, Salário, Data de Admissão, Data de Rescisão (conforme códigos SEFIP).
Tipo e Valor do Aviso Prévio Indenizado (no valor do aviso prévio indenizado já deverá 
 estar incluída a parcela referente ao 13° salário indenizado). Data de Termino do Contrato (quando
 se tratar de rescisão antecipada de contrato a termo por iniciativa do empregador).
*/
SELECT RA_FILIAL AS FILIAL, RA.RA_MAT AS MAT, RA_NOME AS NOME, RA_CC AS CODCCUSTO, CT.CTT_DESC01 AS DESCCUSTO, RA_PIS AS PIS,  
	RA_SALARIO AS SALARIO, RJ.RJ_DESC AS FUNCAO, RA_SITFOLH AS SITUACAO, CODTPDEMISS='', DESCTPDEMISS='', 
	VALOR='', CONVERT(VARCHAR, CAST(RA_ADMISSA AS DATETIME), 103) AS DTADMISSAO, DTDEMISSAO='', DTGERACAO='', DTEXPERIEN=''
	FROM SRA010 RA
INNER JOIN CTT010 CT ON RA.RA_CC = CT.CTT_CUSTO
INNER JOIN SRJ010 RJ ON RA.RA_CODFUNC = RJ.RJ_FUNCAO
WHERE RA_SITFOLH <> 'D'
AND RA_FILIAL = '034NE001'
UNION ALL
SELECT RG_FILIAL, RG_MAT, RA.RA_NOME, RA.RA_CC, CT.CTT_DESC01, RA.RA_PIS, 
RA.RA_SALARIO, RJ.RJ_DESC, RA.RA_SITFOLH, RG.RG_TIPORES, LEFT(RX.RX_TXT,30),
ISNULL((SELECT SUM(RR9.RR_VALOR) FROM SRG010 RG9
INNER JOIN SRR010 RR9 ON RG9.RG_FILIAL = RR9.RR_FILIAL AND RG9.RG_MAT = RR9.RR_MAT
	AND RR9.RR_TIPO3<>'F'
WHERE RG9.RG_DATADEM >= '20140101'
AND RG9.RG_FILIAL = '034NE001'
AND RR9.RR_PD IN ('245','271','301','303','316','317')
AND RG.RG_MAT = RR9.RR_MAT
GROUP BY RG9.RG_FILIAL, RR9.RR_MAT),'') AS VALOR, 
CONVERT(VARCHAR, CAST(RA.RA_ADMISSA AS DATETIME), 103), CONVERT(VARCHAR, CAST(RG.RG_DATADEM AS DATETIME), 103), 
CONVERT(VARCHAR, CAST(MIN(RG.RG_DTGERAR) AS DATETIME), 103) AS RG_DTGERAR,
(CASE 
	WHEN RG.RG_TIPORES IN ('04','05','13') AND RG.RG_DATADEM < RA.RA_VCTEXP2 
		THEN
			CASE 
				WHEN RG.RG_DATADEM < RA.RA_VCTOEXP 
					THEN CONVERT(VARCHAR, CAST(RA.RA_VCTOEXP AS DATETIME), 103) 
				ELSE CONVERT(VARCHAR, CAST(RA.RA_VCTEXP2 AS DATETIME), 103) 
			END
	ELSE '' 
END) AS DTEXPER
FROM SRG010 RG
INNER JOIN SRA010 RA ON RA.RA_FILIAL = RG.RG_FILIAL AND RA.RA_MAT = RG.RG_MAT
INNER JOIN CTT010 CT ON RA.RA_CC = CT.CTT_CUSTO
INNER JOIN SRX010 RX ON RX.RX_COD = RG.RG_TIPORES AND RX.RX_TIP='32' AND RX.D_E_L_E_T_=''
INNER JOIN SRJ010 RJ ON RA.RA_CODFUNC = RJ.RJ_FUNCAO
WHERE RG_DATADEM >= '20140101'
AND RG_FILIAL = '034NE001'
--AND RG.RG_TIPORES IN ('04','05','13')
--AND RG.RG_DATADEM < RA.RA_VCTOEXP
--AND RG.RG_DATADEM < RA.RA_VCTEXP2
GROUP BY RG_FILIAL, RG_MAT, RA.RA_NOME, RA.RA_CC, CT.CTT_DESC01, RA.RA_PIS, RA.RA_ADMISSA, 
RA.RA_SALARIO, RJ.RJ_DESC, RA.RA_SITFOLH, RG.RG_TIPORES, LEFT(RX.RX_TXT,30),RG.RG_DATADEM,
RA.RA_VCTOEXP, RA.RA_VCTEXP2
 

/*
Lista de empregados Transferidos contendo os campos: Nome, PIS, Data da Transferência e
CNPJ de entrada e saída.
*/ 
SELECT RA.RA_FILIAL, RA.RA_MAT AS MAT, RA.RA_NOME AS NOME, RA.RA_PIS AS PIS, 
 CONVERT(VARCHAR, CAST(RE.RE_DATA AS DATETIME), 103) AS DTTRANSF, 
 RE.RE_FILIALD AS FILIALDE, RE.RE_FILIALP AS FILIALPARA, RE.RE_MATD AS MATRDE, RE.RE_MATP AS MATRPARA,
 RE.RE_CCD AS CCUSTODE, RE.RE_CCP AS CCUSTOPARA,
 (SELECT SUBSTRING(Z15_CNPJ,1,3)+'.'+SUBSTRING(Z15_CNPJ,3,3)+'.'+SUBSTRING(Z15_CNPJ,6,3)+'/'+
	SUBSTRING(Z15_CNPJ,9,4)+'-'+SUBSTRING(Z15_CNPJ,13,2)  FROM Z15010
	WHERE LEFT(RE.RE_FILIALD,3) = Z15_EMP) AS CNPJDE,
 (SELECT SUBSTRING(Z15_CNPJ,1,3)+'.'+SUBSTRING(Z15_CNPJ,3,3)+'.'+SUBSTRING(Z15_CNPJ,6,3)+'/'+
	SUBSTRING(Z15_CNPJ,9,4)+'-'+SUBSTRING(Z15_CNPJ,13,2)  FROM Z15010
	WHERE LEFT(RE.RE_FILIALP,3) = Z15_EMP) AS CNPJPARA
FROM SRE010 RE
INNER JOIN SRA010 RA ON RA.RA_FILIAL = RE.RE_FILIALP AND RA.RA_MAT = RE.RE_MATP AND RA.RA_CC = RE.RE_CCP
INNER JOIN Z15010 ON LEFT(RE.RE_FILIALD,3) = Z15_EMP
WHERE RE_DATA >= '20140101'
AND RE_FILIALD='034NE001' OR RE_FILIALP='034NE001'

 