SELECT RD_MAT, RD_PD, RD_CC, SUM(RD_VALOR) FROM SRD010 RD
INNER JOIN SRA010 RA ON RA.RA_FILIAL=RD.RD_FILIAL AND RA.RA_MAT=RD.RD_MAT AND RA.RA_CC=RD.RD_CC
WHERE 
RD_PD IN ('751','731')
AND RD_FILIAL = '001NE001'
AND RD_DATARQ = '201405'
AND RD.D_E_L_E_T_=''
--AND RD_CC = '020000003'
AND RA.RA_SITFOLH<>'D'
GROUP BY RD_MAT, RD_PD, RD_CC
UNION ALL
SELECT RD_MAT, '731' AS "RD_PD", RD_CC, SUM(RD_VALOR) FROM SRD010 RD
INNER JOIN SRA010 RA ON RA.RA_FILIAL=RD.RD_FILIAL AND RA.RA_MAT=RD.RD_MAT AND RA.RA_CC=RD.RD_CC
WHERE 
RD_PD IN ('731', '735')
AND RD_FILIAL = '001NE001'
AND RD_DATARQ = '201405'
AND RD.D_E_L_E_T_=''
--AND RD_CC = '020000003'
AND RA.RA_SITFOLH='D'
GROUP BY RD_MAT, RD_CC
UNION ALL
SELECT RD_MAT, '751' AS "RD_PD", RD_CC, SUM(RD_VALOR) FROM SRD010 RD
INNER JOIN SRA010 RA ON RA.RA_FILIAL=RD.RD_FILIAL AND RA.RA_MAT=RD.RD_MAT AND RA.RA_CC=RD.RD_CC
WHERE 
RD_PD IN ('510', '751')
AND RD_FILIAL = '001NE001'
AND RD_DATARQ = '201405'
AND RD.D_E_L_E_T_=''
--AND RD_CC = '020000003'
AND RA.RA_SITFOLH='D'
GROUP BY RD_MAT, RD_CC
UNION ALL
SELECT RE_MATD, RD.RD_PD,RE_CCD,  SUM(RD.RD_VALOR) FROM SRE010 RE
INNER JOIN SRD010 RD ON RE.RE_FILIALP=RD.RD_FILIAL AND RE.RE_MATP=RD.RD_MAT AND RE.RE_CCP=RD.RD_CC
INNER JOIN SRA010 RA ON RA.RA_FILIAL=RD.RD_FILIAL AND RA.RA_MAT=RD.RD_MAT AND RA.RA_CC=RD.RD_CC
WHERE RE_FILIALD = '001NE001'
AND SUBSTRING(RE.RE_DATA,1,6)='201405'
AND RD_PD IN ('751','731')
AND RD_DATARQ = '201405'
--AND RA.RA_SITFOLH='T'
--AND RE_CCD = '020000003'
GROUP BY RE_MATD, RE_CCD, RD.RD_PD
ORDER BY 3,1,2



SELECT RD_MAT, RD_PD, RD_CC, SUM(RD_VALOR) FROM SRD010 RD
INNER JOIN SRA010 RA ON RA.RA_FILIAL=RD.RD_FILIAL AND RA.RA_MAT=RD.RD_MAT AND RA.RA_CC=RD.RD_CC
WHERE 
RD_PD IN ('751','731')
AND RD_FILIAL = '001NE001'
AND RD_DATARQ = '201405'
AND RD.D_E_L_E_T_=''
--AND RD_CC = '010000001'
AND RA.RA_SITFOLH<>'D'
GROUP BY RD_MAT, RD_PD, RD_CC
UNION ALL
SELECT RD_MAT, '731' AS "RD_PD", RD_CC, SUM(RD_VALOR) FROM SRD010 RD
INNER JOIN SRA010 RA ON RA.RA_FILIAL=RD.RD_FILIAL AND RA.RA_MAT=RD.RD_MAT AND RA.RA_CC=RD.RD_CC
WHERE 
RD_PD IN ('731', '735')
AND RD_FILIAL = '001NE001'
AND RD_DATARQ = '201405'
AND RD.D_E_L_E_T_=''
--AND RD_CC = '010000001'
AND RA.RA_SITFOLH='D'
GROUP BY RD_MAT, RD_CC
UNION ALL
SELECT RD_MAT, '751' AS "RD_PD", RD_CC, SUM(RD_VALOR) FROM SRD010 RD
INNER JOIN SRA010 RA ON RA.RA_FILIAL=RD.RD_FILIAL AND RA.RA_MAT=RD.RD_MAT AND RA.RA_CC=RD.RD_CC
WHERE 
RD_PD IN ('510', '751')
AND RD_FILIAL = '001NE001'
AND RD_DATARQ = '201405'
AND RD.D_E_L_E_T_=''
--AND RD_CC = '010000001'
AND RA.RA_SITFOLH='D'
GROUP BY RD_MAT, RD_CC
UNION ALL
SELECT RE_MATD, RE_CCD, RD.RD_PD, SUM(RD.RD_VALOR) FROM SRE010 RE
INNER JOIN SRD010 RD ON RE.RE_FILIALP=RD.RD_FILIAL AND RE.RE_MATP=RD.RD_MAT AND RE.RE_CCP=RD.RD_CC
INNER JOIN SRA010 RA ON RA.RA_FILIAL=RD.RD_FILIAL AND RA.RA_MAT=RD.RD_MAT AND RA.RA_CC=RD.RD_CC
WHERE RE_FILIALD = '001NE001'
AND SUBSTRING(RE.RE_DATA,1,6)='201405'
AND RD_PD IN ('751','731')
AND RD_DATARQ = '201405'
--AND RA.RA_SITFOLH='T'
--AND RE_CCD = '020000003'
GROUP BY RE_MATD, RE_CCD, RD.RD_PD
ORDER BY  3, 1, 2