 SELECT 
D2_FILIAL AS FILIAL,  
M0_FILIAL AS NOME_FILIAL,
D2_SERIE AS SERIE, 
D2_DOC  AS NFISCAL, 
D2_CLIENTE AS COD_CLI, 
D2_LOJA AS LOJA, 
A1_NOME AS NOME_CLI, 
D2_QUANT AS QUANT,  
D2_UM  AS UM,  
D2_PRCVEN  AS PRC_UNIT, 
D2_TOTAL AS TOTAL, 
D2_ITEM AS ITEM, 
D2_COD  AS COD_PRO, 
C6_DESCRI AS DESCRICAO, 
D2_EMISSAO AS EMISSAO, 
F2_DTLANC AS CONTABIL, 
C5_XINIMED AS MED_INI, 
C5_XFIMMED AS MED_FIM,  
C5_XTPCTB AS CONTABILIZACAO,  
--A1_XTPFLUX AS SEGMENTO,                 
C5_NUM     AS NUMPED,                 
C5_EMISSAO AS EMISPED,                 
C6_XCCUSTO AS CCUSTO                  
FROM SD2010 D2  
 INNER JOIN  SA1010 A1  
  ON A1.D_E_L_E_T_='' 
  AND D2_CLIENTE = A1_COD 
  AND D2_LOJA = A1_LOJA 
 INNER JOIN SC6010 C6 
  ON C6.D_E_L_E_T_='' 
  AND D2_FILIAL = C6_FILIAL  
  AND D2_PEDIDO = C6_NUM 
  AND D2_COD = C6_PRODUTO 
  AND D2_CLIENTE  = C6_CLI 
  AND D2_LOJA = C6_LOJA 
  AND D2_ITEMPV = C6_ITEM  
 INNER JOIN SC5010 C5 
  ON C5.D_E_L_E_T_='' 
  AND C5_FILIAL = C6_FILIAL 
  AND C5_NUM = C6_NUM 
  AND C5_CLIENTE = C6_CLI 
  AND C5_LOJACLI = C6_LOJA 
 INNER JOIN SF2010 F2 
  ON F2.D_E_L_E_T_='' 
  AND F2_FILIAL = D2_FILIAL 
  AND F2_SERIE = D2_SERIE 
  AND F2_DOC = D2_DOC 
  AND F2_CLIENTE = D2_CLIENTE 
  AND F2_LOJA = D2_LOJA
  INNER JOIN SIGAMATTEMP 
  ON SIGAMATTEMP.D_E_L_E_T_=''  
  AND M0_CODIGO='01' AND M0_CODFIL= D2_FILIAL
  WHERE D2.D_E_L_E_T_='' 
AND D2_FILIAL BETWEEN '' AND 'ZZZZZZ'   
AND D2_EMISSAO BETWEEN '20090101' AND '20121231'   
UNION ALL
SELECT 
D2_FILIAL AS FILIAL,  
M0_FILIAL AS NOME_FILIAL,
D2_SERIE AS SERIE, 
D2_DOC  AS NFISCAL, 
D2_CLIENTE AS COD_CLI, 
D2_LOJA AS LOJA, 
A1_NOME AS NOME_CLI, 
D2_QUANT AS QUANT,  
D2_UM  AS UM,  
D2_PRCVEN  AS PRC_UNIT, 
D2_TOTAL AS TOTAL, 
D2_ITEM AS ITEM, 
D2_COD  AS COD_PRO, 
C6_DESCRI AS DESCRICAO, 
D2_EMISSAO AS EMISSAO, 
F2_DTLANC AS CONTABIL, 
C5_XINIMED AS MED_INI, 
C5_XFIMMED AS MED_FIM,  
C5_XTPCTB AS CONTABILIZACAO,  
--A1_XTPFLUX AS SEGMENTO,                 
C5_NUM     AS NUMPED,                 
C5_EMISSAO AS EMISPED,                 
C6_XCCUSTO AS CCUSTO                  
FROM SD2020 D2  
 INNER JOIN  SA1020 A1  
  ON A1.D_E_L_E_T_='' 
  AND D2_CLIENTE = A1_COD 
  AND D2_LOJA = A1_LOJA 
 INNER JOIN SC6020 C6 
  ON C6.D_E_L_E_T_='' 
  AND D2_FILIAL = C6_FILIAL  
  AND D2_PEDIDO = C6_NUM 
  AND D2_COD = C6_PRODUTO 
  AND D2_CLIENTE  = C6_CLI 
  AND D2_LOJA = C6_LOJA 
  AND D2_ITEMPV = C6_ITEM  
 INNER JOIN SC5020 C5 
  ON C5.D_E_L_E_T_='' 
  AND C5_FILIAL = C6_FILIAL 
  AND C5_NUM = C6_NUM 
  AND C5_CLIENTE = C6_CLI 
  AND C5_LOJACLI = C6_LOJA 
 INNER JOIN SF2020 F2 
  ON F2.D_E_L_E_T_='' 
  AND F2_FILIAL = D2_FILIAL 
  AND F2_SERIE = D2_SERIE 
  AND F2_DOC = D2_DOC 
  AND F2_CLIENTE = D2_CLIENTE 
  AND F2_LOJA = D2_LOJA
  INNER JOIN SIGAMATTEMP 
  ON SIGAMATTEMP.D_E_L_E_T_=''  
  AND M0_CODIGO='02' AND M0_CODFIL= D2_FILIAL
  WHERE D2.D_E_L_E_T_='' 
AND D2_FILIAL BETWEEN '' AND 'ZZZZZZ'   
AND D2_EMISSAO BETWEEN '20090101' AND '20121231'   
ORDER BY D2_FILIAL, D2_SERIE, D2_DOC, D2_ITEM
