--SALDOS EM ESTOQUE
select ZZD_VEND as Vendedor, ZZD_PRODUT as Produto, BE_LOCAL as Armazem, BE_LOCALIZ as Rua,
Sum(BF_QUANT ) as QtdRemessa, Sum(BF_EMPENHO) as Empenhados,
ZZD_NUMNF as Num_NF, ZZD_SERNF as Serie, SUM(ZZD_QTDVEN) As Qtd_NF, SUM(BF_QUANT-BF_EMPENHO) AS Qtd_Disp
from ZZD010
INNER JOIN SBE010 ON BE_LOCALIZ=ZZD_VEND AND SBE010.D_E_L_E_T_=''
INNER JOIN ZZ5010 ON ZZ5_NUMNF = ZZD_NUMNF AND ZZ5_SERNF=ZZD_SERNF AND ZZ5_TIPONF='S' AND ZZ5_INTOK<>'S' AND ZZ5010.D_E_L_E_T_=''
LEFT JOIN SBF010 ON BF_PRODUTO=ZZD_PRODUT AND BF_LOCAL=BE_LOCAL AND BF_LOCALIZ=ZZD_VEND AND SBF010.D_E_L_E_T_=''
WHERE ZZD_DATINT='' AND ( (BF_PRODUTO IS NULL)  OR (BF_QUANT<=0) OR (BF_QUANT-BF_EMPENHO < ZZD_QTDVEN) ) 
GROUP BY ZZD_VEND,ZZD_PRODUT,BE_LOCAL,BE_LOCALIZ,ZZD_NUMNF,ZZD_SERNF
order by ZZD_VEND,BE_LOCAL,BE_LOCALIZ,ZZD_NUMNF,ZZD_SERNF,ZZD_PRODUT

--ORDER BY ZZD_VEND



--RECEBIMENTOS PENDENTES
sELECT * 
--UPDATE ZZE010 SET ZZE_DATINT='20130409',ZZE_HORINT=000000 
		FROM ZZE010 ZZE 
		INNER JOIN ZZF010 ZZF ON ZZF_FILIAL = ZZE_FILIAL AND ZZF_VEND = ZZE_VEND AND ZZF_FATURA = ZZE_FATURA AND ZZF.D_E_L_E_T_ = ' ' 
		INNER JOIN ZZC010 ZZC ON ZZC_FILIAL = ZZF_FILIAL AND ZZC_VEND = ZZF_VEND AND ZZC_NUMNF = ZZF_NUMNF AND ZZC_SERNF = ZZF_SERNF AND ZZC.D_E_L_E_T_ = ' ' 
		WHERE  
		ZZE_DATINT = ' '     
		AND ZZE.D_E_L_E_T_ = ' ' 
		AND ZZC_TIPVEN in ('0','3')
		ORDER BY ZZE_VEND, ZZE_FATURA

--NFS PENDENTES
SELECT * 
--UPDATE ZZC010 SET ZZC_DATINT='20130409',ZZC_HORINT=000000
select * 
FROM ZZC010 WHERE ZZC_DATINT='' AND D_E_L_E_T_=''


select * from SBF010 WHERE BF_EMPENHO>0 AND SUBSTRING(BF_PRODUTO,1,1)='Z' AND D_E_L_E_T_=''


SELECT * FROM SBF010 WHERE BF_LOCALIZ='0102' AND D_E_L_E_T_='' AND BF_QUANT>0
SELECT * FROM SDB010 WHERE D3_LOCALIZ='0101' AND D3_EMISSAO > '20130903'

SELECT * FROM ZZG010
UPDATE ZZH010 SET ZZH_DATINT='20130904',ZZH_HORINT=000000
WHERE ZZH_DATINT=''

UPDATE ZZ0010 SET ZZ0_DATINT='20130904',ZZ0_HORINT=000000
WHERE ZZ0_DATINT=''

SELECT * FROM ZZ0010 WHERE ZZ0_DATINT=''
SELECT * FROM ZZ4010 WHERE ZZ4_DATINT=''

SELECT * FROM ZZ5010 WHERE ZZ5_DATINT=''
SELECT * FROM ZZ7010 WHERE ZZ7_DATINT=''
SELECT * FROM ZZ9010 WHERE ZZ9_DATINT=''
SELECT * FROM ZZD010
--UPDATE ZZD010 SET ZZD_DATINT='20130904',ZZD_HORINT=000000 
WHERE ZZD_DATINT=''