

-- TENTATIVA DE AGRUPAR PARA SOMAR VALORES DE HORAS E VALOR.
select RV_TIPO,RA_FILIAL,RA_MAT,RA_NOME,RA_CIC,RV_COD,  
case when RV_TIPO='H' then SUM(RD_HORAS)
     when RV_TIPO='V' then SUM(RD_VALOR)
	 when RV_TIPO='D' then SUM(RD_HORAS)*8
end VTIPOVERBA
from SRA010 A,SRD010 B,SRV010 C
where RA_FILIAL = RD_FILIAL and RA_MAT = RD_MAT and RD_PD = RV_COD and
RD_DATARQ >= '201201' and RA_SITFOLH <> 'D' and RV_MED13 = 'S'
and A.D_E_L_E_T_ = ' '
and B.D_E_L_E_T_ = ' '
and C.D_E_L_E_T_ = ' ' 
Group by RA_FILIAL,RA_MAT,RA_NOME,RA_CIC,RV_COD,RV_TIPO
ORDER BY RA_FILIAL,RA_MAT,RA_NOME,RA_CIC,RV_COD,RV_TIPO

---ORIGINAL DA LE
select RA_FILIAL,RA_MAT,RA_NOME,RA_CIC,RA_CC,RA_SITFOLH,RD_PD,RV_DESC,RD_HORAS,RD_VALOR,RD_DATARQ
from SRA010 A,SRD010 B,SRV010 C
where RA_FILIAL = RD_FILIAL and RA_MAT = RD_MAT and RD_PD = RV_COD and
RD_DATARQ >= '201201' and RA_SITFOLH <> 'D' and RV_MED13 = 'S' and RA_MAT ='000005'
and A.D_E_L_E_T_ = ' '
and B.D_E_L_E_T_ = ' '
and C.D_E_L_E_T_ = ' ' 


