SELECT RA_FILIAL,RA_MAT,RTRIM(RA_NOME),RA_CIC,RA_ADMISSA,RJ_DESC,RA_CC, RH_CHAMADO, RH_DATAINI
FROM SRA010 A, SRJ010 B, SRH010 C
WHERE
A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
AND RA_CODFUNC = RJ_FUNCAO
AND RA_FILIAL = RH_FILIAL
AND RA_MAT = RH_MAT
AND RA_SITFOLH <> 'D'
AND RA_RESCRAI <> '31'
AND RH_DATAINI >= '20130301'


SELECT RR_FILIAL,RR_MAT,RTRIM(RA_NOME),RH_SALMES,RH_DATAINI,RH_DFERIAS,RH_DABONPE,RR_PD,RV_DESC,RR_VALOR
FROM SRA010 A , SRH010 B, SRR010 C, SRV010 D
WHERE
A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND D.D_E_L_E_T_ = ' '
AND RR_PD = RV_COD
AND RA_FILIAL = RR_FILIAL
AND RA_FILIAL = RH_FILIAL
AND RA_MAT = RR_MAT
AND RA_MAT = RH_MAT
AND RH_DATAINI >= '20130301'

SELECT RA_SINDICA, * FROM SRA010 WHERE D_E_L_E_T_ = ' '
AND RA_FILIAL = '022NE002'
AND RA_SITFOLH <> 'D'
AND RA_CATFUNC <> 'A'
AND RA_SINDICA = '43'


SELECT Substring(RA_NOME,1,charindex(' ',RA_NOME)) NOME,Substring(RA_NOMECMP,1,charindex(' ',RA_NOMECMP)) NOMECMP,* 
FROM SRA010
WHERE RA_NOMECMP <> ''
AND RA_NOME <> RA_NOMECMP

select * FROM RCE010 WHERE D_E_L_E_T_ = ' 'AND RCE_CGC = '01039667000160'




