
select RA_FILIAL, RA_CC, RA_MAT, RA_NOME, RJ_DESC, RA_ADMISSA, RF_DATABAS, RF_DFERVAT, RF_DFALVAT, RF_DFERAAT, RF_DFALAAT, RA_LOTACA_
,ISNULL((SELECT TOP 1 X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'LT'AND X5_CHAVE = RA_LOTACA_ AND D_E_L_E_T_ = ' '),' ')LOTACAO
FROM SRA010 A, SRF010 B, SRJ010 C
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND RA_CODFUNC = RJ_FUNCAO
AND RA_FILIAL = RF_FILIAL
AND RA_MAT = RF_MAT
AND RA_FILIAL = '014NE006'
AND RA_SITFOLH <> 'D'


SELECT RA_MAT, RA_NOME, RA_DEMISSA FROM SRA010 WHERE D_E_L_E_T_ = ' '
AND RA_FILIAL = '014NE001'
AND RA_DEMISSA >= '20130201'

select * from SRR010 where D_E_L_E_T_ = ' '

SELECT RR_FILIAL, RR_MAT,RH_SALMES, RH_DATAINI, RH_DFERIAS, RH_DABONPE, RR_PD, RR_VALOR
FROM SRH010 A, SRR010 B
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND RH_FILIAL = RR_FILIAL
AND RH_MAT = RR_MAT
AND RR_DATA = RH_DTRECIB
AND RH_DATAINI > = '20130201'
AND RR_PD < '500'
AND SUBSTRING(RR_FILIAL,1,3) = '002'
ORDER BY RR_FILIAL, RR_MAT

SELECT * FROM SRA010 WHERE D_E_L_E_T_ = ' '
AND SUBSTRING(RA_FILIAL,1,3) = '002'