select * from SRV010 where D_E_L_E_T_ = ' '
AND RA_FILIAL >= '022NE001'

SELECT RA_FILIAL, RA_MAT, RA_NOME, RA_SITFOLH FROM SRA010 WHERE D_E_L_E_T_ = ' '
AND SUBSTRING(RA_FILIAL,1,3) = '014'


SELECT SUM(RD_VALOR) FROM SRD010 WHERE D_E_L_E_T_ = ' '
AND RD_DATARQ = '201302'
AND RD_PD = '058'
AND SUBSTRING(RD_FILIAL,1,3) = '014'

SELECT SUM(RD_VALOR) FROM SRD010 WHERE D_E_L_E_T_ = ' '
AND RD_DATARQ = '201302'
AND RD_PD IN ('049','050')
AND SUBSTRING(RD_FILIAL,1,3) = '014'

SELECT RD_FILIAL, RD_MAT, RA_NOME, RA_SALARIO,RA_CIC,RD_CC, RD_PD, RV_DESC, RD_HORAS, RD_VALOR, RD_DATARQ   
FROM SRD010 A, SRA010 B, SRV010 C
WHERE A.D_E_L_E_T_ = ' '
AND B. D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND RA_FILIAL = RD_FILIAL
AND RA_MAT = RD_MAT
AND RD_PD = RV_COD
AND RD_DATARQ >= '201302'
AND RD_VALOR <> '0'
AND RD_PD = '690'


SELECT RD_FILIAL, RD_MAT, RA_NOME, RA_CIC,RD_CC, RD_PD, RV_DESC, RD_HORAS, RD_VALOR, RD_DATARQ   
FROM SRD010 A, SRA010 B, SRV010 C
WHERE A.D_E_L_E_T_ = ' '
AND B. D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND RA_FILIAL = RD_FILIAL
AND RA_MAT = RD_MAT
AND RD_PD = RV_COD
AND RD_DATARQ >= '201201'
AND RD_VALOR <> '0'
AND RD_PD IN ('262','A01')



SELECT * FROM SRG010 WHERE D_E_L_E_T_ = ' '
AND RG_DATADEM >= '20130301'

SELECT RA_FILIAL,RA_CC,RA_MAT,RTRIM(RA_NOME),RA_CIC,RA_ADMISSA,RG_TIPORES,RA_DEMISSA,RJ_DESC,RG_CHAMADO 
FROM SRA010 A, SRJ010 B, SRG010 C
WHERE
A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
AND RA_FILIAL = RG_FILIAL
AND RA_MAT = RG_MAT
AND RA_CODFUNC = RJ_FUNCAO
AND RA_SITFOLH = 'D'
AND RA_RESCRAI <> '31'
AND RA_DEMISSA >= '20130301'


SELECT RA_FILIAL,RA_MAT,RTRIM(RA_NOME),RA_CIC,RA_ADMISSA,RJ_DESC,RA_CC, RH_CHAMADO, RH_DATAINI, RF_DATABAS, RF_DATAINI, RF_CHAMADO
FROM SRA010 A, SRJ010 B, SRH010 C, SRF010 D
WHERE
A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
AND D.D_E_L_E_T_ = ' '
AND RH_DATABAS = RF_DATABAS
AND RH_MAT = RF_MAT
AND RH_FILIAL = RF_FILIAL
AND RA_CODFUNC = RJ_FUNCAO
AND RA_FILIAL = RH_FILIAL
AND RA_MAT = RH_MAT
AND RH_DATAINI >= '20130301'
AND RH_MAT = '035817'


SELECT * FROM SRH010 WHERE RH_DATAINI >= '20130301'
AND RH_MAT = '035817'