SELECT DISTINCT(RA_FILIAL) FROM SRA010
WHERE RA_SINDICA ='67'
AND RA_SITFOLH<>'D'

SELECT DISTINCT(RA_SINDICA) FROM SRA010
WHERE RA_FILIAL='023NE001'
AND RA_SITFOLH<>'D'

SELECT RA_SINDICA,* FROM SRA010
WHERE RA_FILIAL IN ('022NE005')
AND RA_SINDICA IN ('67','76')
AND RA_ASSIST = '1'
AND RA_SITFOLH<>'D'

SELECT RD.RD_FILIAL, RD.RD_MAT, RA.RA_NOME , RD.RD_PD, RV.RV_DESC, RD.RD_VALOR, 
SUBSTRING(RD.RD_DATARQ, 5,2 )+'/'+ SUBSTRING(RD.RD_DATARQ, 1,4 ) AS RD_DATARQ,              
RD.RD_DATPGT FROM  SRD010 RD
INNER JOIN SRA010 RA ON RA.RA_FILIAL=RD .RD_FILIAL AND RA .RA_MAT= RD.RD_MAT AND RD.RD_CC =RA.RA_CC
INNER JOIN SRV010 RV ON RD.RD_PD=RV.RV_COD AND RV.D_E_L_E_T_= ''
WHERE RD_DATARQ BETWEEN '201403' AND '201405'
AND RD.RD_FILIAL='022NE005'
AND RD_PD IN('592') 
AND RD.D_E_L_E_T_=''