SELECT RC_FILIAL, RC_MAT, RTRIM(RA_NOME), RA_SITFOLH, RC_PD, RV_DESC, RC_TIPO1, RC_HORAS, RC_VALOR, RC_TIPO2, RC_DATA
FROM SRC010 A, SRA010 B, SRV010 C
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND RA_FILIAL = RC_FILIAL
AND RA_MAT = RC_MAT
AND RC_PD = RV_COD
AND RC_FILIAL = '022NE002'


AND RC_MAT = '000311'


SELECT * FROM SRV010 WHERE D_E_L_E_T_ = ' '
AND RA_FILIAL = '022NE005'


SELECT  * FROM SRA010 WHERE D_E_L_E_T_ = ' ' 
ORDER BY RA_NOME