SELECT RD_FILIAL,RD_MAT,RA_NOME,RD_PD,RV_DESC,SUBSTRING(RD_DATPGT,1,6)ANOMES,SUM(RD_VALOR) IR_RETIDO
FROM SRD010 SRD, SRV010 SRV, SRA010 SRA
WHERE
SRD.D_E_L_E_T_ = ' '
AND SRV.D_E_L_E_T_ = ' '
AND SRA.D_E_L_E_T_ = ''
AND RA_FILIAL = RD_FILIAL
AND RA_MAT = RD_MAT
AND RD_PD = RV_COD
AND RD_EMPRESA = ''
--AND RV_CODFOL IN ('012','152','101','071','066','009','067')
AND RV_DIRF IN ('D','L')
AND SUBSTRING(RD_FILIAL, 1,3) = '014'
AND SUBSTRING(RD_DATPGT,1,4) = '2012'
GROUP BY RD_FILIAL,RD_MAT,RA_NOME,RD_PD,RV_DESC,SUBSTRING(RD_DATPGT,1,6)

