select RA_FILIAL, RA_MAT, RA_NOME, RJ_DESC, RA_CC, RD_PD, RV_DESC, RD_VALOR, RD_DATARQ, RD_CC 
from SRA010 A, SRD010 B, SRV010 C , SRJ010 D
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND D.D_E_L_E_T_ = ' '
AND RA_MAT = RD_MAT
and RA_FILIAL = RD_FILIAL
AND RD_PD = RV_COD
AND RA_CODFUNC = RJ_FUNCAO
AND RD_DATARQ >= '201201'
AND SUBSTRING(RD_CC,1,5) = '07001'


select * from SRG010 WHERE D_E_L_E_T_ = ' '
AND RG_DATADEM = '20130122'
AND RG_FILIAL = '014NE004'

select * from SRA010 WHERE D_E_L_E_T_ = ' '
AND RA_DEMISSA = '20130122'
AND RA_FILIAL = '014NE004'
AND RA_CC = '021080201'


SELECT Substring(RA_NOME,1,charindex(' ',RA_NOME)) NOME,Substring(RA_NOMECMP,1,charindex(' ',RA_NOMECMP)) NOMECMP,* 
FROM SRA010
WHERE RA_NOMECMP <> ''
AND RA_NOME <> RA_NOMECMP

AND RG_CC = '21080201'