SELECT T.*,ROUND((PROV_FEV - PROV_JAN),2) DIF
 FROM(
SELECT RA_FILIAL,RA_MAT,RA_NOME,RA_CC,RA_ADMISSA,RA_SITFOLH,RA_SALARIO,RA_PERICUL
,ROUND(ISNULL((SELECT TOP 1 RT_SALARIO FROM SRT010 WHERE D_E_L_E_T_ = '' AND RT_FILIAL = RA_FILIAL AND RA_MAT = RT_MAT AND RT_DATACAL = '20130131' AND RT_SALARIO > 0),0),2) PROV_JAN
,ROUND(ISNULL((SELECT TOP 1 RT_SALARIO FROM SRT010 WHERE D_E_L_E_T_ = '' AND RT_FILIAL = RA_FILIAL AND RA_MAT = RT_MAT AND RT_DATACAL = '20130228' AND RT_SALARIO > 0),0),2) PROV_FEV
FROM SRA010
WHERE 
    D_E_L_E_T_ = ''
AND RA_SITFOLH <> 'D')T 
WHERE PROV_JAN <> PROV_FEV
AND SUBSTRING(RA_FILIAL,1,3) = '014'
ORDER BY 1,2

SELECT * FROM SRL010 WHERE D_E_L_E_T_ = ' '

SELECT RL_FILIAL, RL_MAT, RL_CPFCGC, RTRIM(RL_BENEFIC)  FROM SRL010 WHERE D_E_L_E_T_ = ' '
ORDER BY RL_BENEFIC

SELECT * FROM SRA010 WHERE D_E_L_E_T_ = ' '
AND RA_CIC ='39705766878'



SELECT RA_FILIAL,RA_MAT,RA_NOME,RA_CIC,RA_ADMISSA,RJ_DESC,CTT_DESC01
FROM SRA010 A, SRJ010 B, CTT010 C
WHERE
A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = '' 
AND RA_SITFOLH <> 'D'
AND RA_ADMISSA >= '20130201'
AND RA_CODFUNC = RJ_FUNCAO
AND RA_CC = CTT_CUSTO


SELECT T.* FROM(
 SELECT dbo.FU_DESEMBARALHA(RA_USERLGI) INCLUSAO,RA_ADMISSA,RA_FILIAL,RA_MAT,RA_NOME,RJ_DESC,CTT_CUSTO,CTT_DESC01 
 FROM SRA010 A, SRJ010 B, CTT010 C
 WHERE RA_CODFUNC = RJ_FUNCAO AND RA_CC = CTT_CUSTO AND
 A.D_E_L_E_T_  = ' ' AND
 B.D_E_L_E_T_  = ' ' AND
 C.D_E_L_E_T_  = ' ')
 T
 WHERE SUBSTRING(INCLUSAO,1,8) >= '20130101'


 select RA_FILIAL,RA_MAT,RA_NOME,RA_CIC,RA_CC,RD_PD,RV_DESC,RD_HORAS,RD_VALOR,RD_DATARQ
from SRA010 A,SRD010 B, SRV010 C
where RA_FILIAL = RD_FILIAL 
and RA_MAT = RD_MAT 
and RD_PD = RV_COD 
and RD_PD in ('123','130','131','132','133','134','135','136','137','138','139','140','141','142','143','144','145','146','147','148','149','150','151','152') 
and RD_DATARQ >= '201301'
and RD_VALOR <> '0'
and A.D_E_L_E_T_ = ' '
and B.D_E_L_E_T_ = ' '
and C.D_E_L_E_T_ = ' '


select RA_FILIAL, RA_MAT, RA_SALARIO,RA_SALINCO FROM SRA010 WHERE D_E_L_E_T_ = ' '
and RA_SITFOLH <> 'D'
AND RA_FILIAL IN ('002NE001','002NE002','002NE003','002NE004')

select RT_FILIAL, RT_MAT, RA_SITFOLH, RA_ADMISSA, RA_SALARIO, RT_VERBA, RT_VALOR 
from SRA010 A, SRT010 B
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND RA_FILIAL = RT_FILIAL
AND RA_MAT = RT_MAT
AND RT_DATACAL = '20130228'
AND RT_VERBA = '953'
ORDER BY RT_FILIAL


SELECT RA_FILIAL, RA_MAT, RA_SITFOLH FROM SRA010 WHERE D_E_L_E_T_ = ' '


SELECT RA_FILIAL,RA_MAT,RA_NOME,RA_CIC,RA_ADMISSA,RA_DEMISSA,RJ_DESC, RA_CC
FROM SRA010 A, SRJ010 B
WHERE
A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND RA_CODFUNC = RJ_FUNCAO
AND RA_SITFOLH = 'D'
AND RA_RESCRAI <> '31'
AND RA_DEMISSA >= '20130201'

SELECT RA_FILIAL, RA_MAT, RA_NOME, RA_CC, RD_PD, RV_DESC, RD_VALOR, RD_DATARQ
 FROM SRA010 A, SRD010 B, SRV010 C
 WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND C.D_E_L_E_T_ = ' '
AND RA_FILIAL = RD_FILIAL
AND RA_MAT = RD_MAT
AND RD_PD = RV_COD
AND RD_PD IN ('364','58D')


SELECT RA_FILIAL, RA_MAT, RA_NOME, RD_PD, RD_VALOR
FROM SRA010 A, SRD010 B
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND RA_FILIAL = RD_FILIAL
AND RA_MAT = RD_MAT
AND RD_PD IN('001','009','021','025','049','058','059','100','130','132','133','137','166','334')
AND RD_DATARQ = '201302'
AND SUBSTRING(RA_FILIAL,1,3) = '014'


select RA_FILIAL, RA_MAT, RA_NOME, RA_CIC, RA_SITFOLH from SRA010 WHERE D_E_L_E_T_ = ' '
ORDER BY RA_NOME


select * from SRJ010 where D_E_L_E_T_ = ' '

SELECT RA_FILIAL,RA_MAT,RA_NOME, RJ_DESC,RA_CIC,RA_ADMISSA,RA_DEMISSA,RA_AFASFGT,RA_CC,RG_DTAVISO
FROM SRA010 A, SRG010 B, SRJ010 C
WHERE
A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
AND RA_CODFUNC = RJ_FUNCAO
AND RA_FILIAL = RG_FILIAL
AND RA_MAT = RG_MAT
AND RA_SITFOLH = 'D'
AND RA_RESCRAI <> '31'
AND RA_DEMISSA >= '20130201'

SELECT RA_FILIAL, RA_MAT, RA_NOME, RD_PD, RD_VALOR
FROM SRA010 A, SRD010 B
WHERE A.D_E_L_E_T_ = ' '
AND B.D_E_L_E_T_ = ' '
AND RA_FILIAL = RD_FILIAL
AND RA_MAT = RD_MAT
AND RD_PD IN ('695', '305')
AND RD_DATARQ = '201302'
order by RA_FILIAL
