SELECT * FROM SRC990
WHERE RC_PD ='999'
ORDER BY 1,2,3

SELECT RG.RG_FILIAL, RG.RG_MAT, RR.RR_DATAPAG, RR.RR_VALOR FROM SRG990 RG
LEFT JOIN SRR990 RR ON RG.RG_FILIAL = RR.RR_FILIAL AND RG.RG_MAT = RR.RR_MAT
AND RG.RG_DATADEM = RR.RR_DATA
WHERE RR.RR_PD = '599'
AND RR.D_E_L_E_T_='' AND RG.D_E_L_E_T_=''
GROUP BY RG.RG_FILIAL, RG.RG_MAT, RR_DATAPAG, RR.RR_VALOR
ORDER BY 1,2


SELECT * FROM SRG990 WHERE RG_MAT = '000032'
SELECT * FROM SRR990
WHERE RR_MAT = '000032'