----CONFORME CALCULO BUILDUP
/*-------
SRT0C0	 |
--------*/

SELECT * INTO SRT0C0X FROM (

SELECT NEW.RT_FILIAL, NEW.RT_MAT, CASE WHEN OLD.RT_CC IS NOT NULL THEN OLD.RT_CC ELSE NEW.RT_CC END AS RT_CC, 
CASE WHEN OLD.RT_DATACAL IS NOT NULL THEN OLD.RT_DATACAL ELSE '20131231' END AS RT_DATACAL, 
NEW.RT_TIPPROV ,
--CASE WHEN NEW.RT_TIPPROV IS NOT NULL THEN NEW.RT_TIPPROV ELSE OLD.RT_TIPPROV END AS RT_TIPPROV,
	NEW.RT_VERBA, NEW.RT_VALOR, 
--OLD.RT_DATABAS, OLD.RT_DFERVEN, OLD.RT_DFERPRO, OLD.RT_SALARIO
ISNULL(OLD.RT_DATABAS,'') AS RT_DATABAS, ISNULL(OLD.RT_DFERVEN,'') AS RT_DFERVEN, ISNULL(OLD.RT_DFERPRO,'')AS DFERPRO, ISNULL(OLD.RT_SALARIO,'') AS RT_SALARIO
 FROM SRTBASE NEW 
LEFT JOIN SRT990 OLD 
	ON OLD.RT_FILIAL = NEW.RT_FILIAL
AND	   OLD.RT_MAT	 = NEW.RT_MAT
AND	   OLD.RT_VERBA	 = NEW.RT_VERBA
AND	   OLD.RT_TIPPROV = NEW.RT_TIPPROV 
WHERE NEW.RT_FILIAL IN ('73')
--AND OLD.RT_SALARIO IS NULL 
AND NEW.RT_MAT <> '005726' -- FUNCIONÁRIO AFASTADO, NÃO CALCULADO PELO PROTHEUS (3654,140007)
) TRB
ORDER BY 2,1,5,6