UPDATE OAO
SET OAO.RV_CREDIT = ODO.RV_CREDIT,
OAO.RV_DEBITO = ODO.RV_DEBITO
FROM srv0A0 AS OAO 
INNER JOIN SRV0D0 AS ODO ON OAO.RV_COD = ODO.RV_COD AND OAO.RV_DESC = ODO.RV_DESC

UPDATE OBO
SET OBO.RV_CREDIT = ODO.RV_CREDIT,
OBO.RV_DEBITO = ODO.RV_DEBITO
FROM srv0B0 AS OBO 
INNER JOIN SRV0D0 AS ODO ON OBO.RV_COD = ODO.RV_COD AND OBO.RV_DESC = ODO.RV_DESC

UPDATE OCO
SET OCO.RV_CREDIT = ODO.RV_CREDIT,
OCO.RV_DEBITO = ODO.RV_DEBITO
FROM srv0C0 AS OCO 
INNER JOIN SRV0D0 AS ODO ON OCO.RV_COD = ODO.RV_COD AND OCO.RV_DESC = ODO.RV_DESC

UPDATE O95O
SET O95O.RV_CREDIT = ODO.RV_CREDIT,
O95O.RV_DEBITO = ODO.RV_DEBITO
FROM srv950 AS O95O 
INNER JOIN SRV0D0 AS ODO ON O95O.RV_COD = ODO.RV_COD AND O95O.RV_DESC = ODO.RV_DESC

UPDATE O96O
SET O96O.RV_CREDIT = ODO.RV_CREDIT,
O96O.RV_DEBITO = ODO.RV_DEBITO
FROM srv960 AS O96O 
INNER JOIN SRV0D0 AS ODO ON O96O.RV_COD = ODO.RV_COD AND O96O.RV_DESC = ODO.RV_DESC

SELECT RV_CREDIT, RV_DEBITO, RV_COD, RV_DESC,* FROM SRV0A0 ORDER BY 3
SELECT RV_CREDIT, RV_DEBITO, RV_COD, RV_DESC,* FROM SRV0B0 ORDER BY 3
SELECT RV_CREDIT, RV_DEBITO, RV_COD, RV_DESC,* FROM SRV0D0 ORDER BY 3

