SELECT Y.* FROM(
SELECT W.* 
,ROUND(ISNULL((SELECT SUM(RC_VALOR)  FROM SRC010 WHERE D_E_L_E_T_ = '' AND RC_FILIAL = R1_FILIAL AND RC_MAT = R1_MAT AND RC_PD = VERBA1),0),2) VALSRC
FROM(
SELECT R1_FILIAL,R1_MAT,VERBA1,ROUND(SUM(R1_VALOR),2) SOMA FROM(
SELECT R1_FILIAL,R1_MAT,R1_VALOR,R1_DATA,R1_PD
,ISNULL((SELECT SUBSTRING(RCC_CONTEU,1,3) FROM RCC010 WHERE RCC_CODIGO = 'U004' AND D_E_L_E_T_ = '' AND SUBSTRING(RCC_CONTEU,1,3) = R1_PD),'') VERBA1
,ISNULL((SELECT SUBSTRING(RCC_CONTEU,4,3) FROM RCC010 WHERE RCC_CODIGO = 'U004' AND D_E_L_E_T_ = '' AND SUBSTRING(RCC_CONTEU,1,3) = R1_PD),'') VERBA2
FROM SR1010 
WHERE SUBSTRING(R1_DATA,1,6) = '201311' 
AND D_E_L_E_T_ = '' )T
WHERE VERBA1 <> ''
GROUP BY R1_FILIAL,R1_MAT,VERBA1
UNION ALL
SELECT R1_FILIAL,R1_MAT,VERBA2,SUM(R1_VALOR) SOMA FROM(
SELECT R1_FILIAL,R1_MAT,R1_VALOR,R1_DATA,R1_PD
,ISNULL((SELECT SUBSTRING(RCC_CONTEU,1,3) FROM RCC010 WHERE RCC_CODIGO = 'U004' AND D_E_L_E_T_ = '' AND SUBSTRING(RCC_CONTEU,1,3) = R1_PD),'') VERBA1
,ISNULL((SELECT SUBSTRING(RCC_CONTEU,4,3) FROM RCC010 WHERE RCC_CODIGO = 'U004' AND D_E_L_E_T_ = '' AND SUBSTRING(RCC_CONTEU,1,3) = R1_PD),'') VERBA2
FROM SR1010 
WHERE SUBSTRING(R1_DATA,1,6) = '201311' 
AND D_E_L_E_T_ = '' )T
WHERE VERBA1 <> ''
GROUP BY R1_FILIAL,R1_MAT,VERBA2)W)Y
WHERE SOMA <> VALSRC
ORDER BY 1,2,3
